### ISSUE TITLE
Desktop font is the wrong colour when using GTK3.

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#1]
Please see the attached screenshots. The GTK3 font colour on the desktop when using MATE 1.14 built against GTK3 is the wrong colour, dark grey instead of white.

## GTK2

![desktop_font_gtk2](https://cloud.githubusercontent.com/assets/304639/15396439/0d12884c-1dd4-11e6-9e56-174c33bb6d82.png)

## GTK3 

![desktop_font_gtk3](https://cloud.githubusercontent.com/assets/304639/15396446/1638eeca-1dd4-11e6-9c3b-c94c88c67814.png)

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/b1f7e47a8899a1938cb4b1e68bc8c8153822988b

**Comment by flexiondotorg** [comment]
I confirm this is fixed :-)

**Comment by raveit65** [comment]
done for radiant theme
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/c10bc6323895ed7e1a058a7ebe9f6cbb39b4b900
