### ISSUE TITLE
GTK3 panels have gradients but GTK2 had flat panels.

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#10]
GTK3 panels have gradients but we prefer the flat look the GTK2 panels had.

## GTK2

![panels_gtk2](https://cloud.githubusercontent.com/assets/304639/15400406/519241f6-1de3-11e6-8016-ee54ec0b81cf.png)

## GTK3

![panels_gtk3](https://cloud.githubusercontent.com/assets/304639/15400417/5b605362-1de3-11e6-93f4-324dfa39c624.png)

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3d5ea5b05acd4f1e82b44aed7d28bc0b19490633

PS: i added a transition effect to menus and buttons. I can do that for other apps too.
Or i can remove it if you don't like it.

**Comment by flexiondotorg** [comment]
I confirm the panels are flat, looks great. Thanks.

I'm not keen on the transition effect though. Can you drop that please. Once that is dropped this can be closed :-)

**Comment by raveit65** [comment]
sadly dropped :)
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/1d99b0eb97dd0b281fcd3a8bbf916e1d5218d25c

**Comment by flexiondotorg** [comment]
Much better :-p

Confirm this as completed.
