### ISSUE TITLE
GTK3 menus are much wider.

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#11]
The menus, in particular `mate-panel`, are very wide in GTK3 than GTK2.

#### Applications
![screenshot at 2016-05-19 17 29 09](https://cloud.githubusercontent.com/assets/13032135/15401480/a0666876-1de7-11e6-8ef7-7a30561fc625.png)
![screenshot at 2016-05-19 17 29 17](https://cloud.githubusercontent.com/assets/13032135/15401484/a06e13fa-1de7-11e6-9cc9-7032386bda0a.png)

#### Places
![screenshot at 2016-05-19 17 29 31](https://cloud.githubusercontent.com/assets/13032135/15401483/a06c40ac-1de7-11e6-926d-551f52507edc.png)
![screenshot at 2016-05-19 17 30 26](https://cloud.githubusercontent.com/assets/13032135/15401479/a06640d0-1de7-11e6-9ec3-b6f1d81d51a0.png)

#### System
![screenshot at 2016-05-19 17 29 58](https://cloud.githubusercontent.com/assets/13032135/15401482/a069dc4a-1de7-11e6-8d58-0fa7fbedd0a2.png)
![screenshot at 2016-05-19 17 30 06](https://cloud.githubusercontent.com/assets/13032135/15401481/a0690ee6-1de7-11e6-9104-18369ae4359a.png)

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/mate-panel/commit/bd3d7bc04d864d37e054b9e51fb48cbabb7e18f7
We set a default icon size (22px), you can set this via gsettings.
For this reason the menus are wider.
Personal, i would adjust the other menus to follow that size.

**Comment by raveit65** [comment]
i guess you're gtk2 version is not updated to 1.14.

**Comment by lah7** [comment]
This is the behaviour under:
* MATE 1.14.0
* GTK2 2.24.30
* GTK3 3.18.9.

------------
Changing schema `org.mate.panel.menubar` **item-icon-size** didn't change much - the width is still pretty wide.

**Comment by flexiondotorg** [comment]
OK, then tweaking that value is going in MATE Tweak :-)

**Comment by raveit65** [comment]
Well i will see to reduce the general padding of  the menus in gtk3.
But someone have set this in the theme :)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9d3a1b808e046c4f41765ba4e5830ee7b734ea25
At least gtk3-inspectot showed me that menuitems was using padding settings from https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L829
I reduced all vertical paddings in this commit, but i've no idea why other menus looks smaller.

**Comment by raveit65** [comment]
I think this depends on size of icons in Ambiant-MATE theme.
Example in Pluma:
In menu **edit** the first menuitem have the same size than menuitems in mate-panel,
but other menuitems are smaller.

**Comment by raveit65** [comment]
Ha, i found the culprit.....
There is a different between
.menubar .menuitem {}    --> menubar item
and
.menu .menuitem {}  --> menuitem itself
But  Mate-Ambiance theme use only 
.menuitem {}
For this reasons menu menuitems use the same settings than menubar menuitems.
So, menus needs a general re-work.

**Comment by raveit65** [comment]
Before i start her i want to say what is possible.
As mentioned before i think menu settings are not valid.
So the only chance i have is to sync all menus, that means in result all menus will be larger than before.
In the end this is a pre-work for gtk+-3.20, here everything needs to be done new.

**Comment by raveit65** [comment]
Guys, i need a statement.

**Comment by flexiondotorg** [comment]
@raveit65 Can you please describe the options for the menu width. I don't quite follow what the potential solutions are. Sounds like the way it is now in GTK3, is how it is going to be? And menus will need reworking for GTK3.20 anyway?

@raveit65 When you say "i think menu settings are not valid" so you mean in the theme or MATE? If the menus being wider, everywhere, is just how is has to be now then I'm fine with that. Particularly if all menus become consistent, which sounds like what you are proposing?

@lah7 Your thoughts?

**Comment by lah7** [comment]
I'm just as confused what the options are and what is responsible for the wider menus. :confused:

> Example in Pluma:
>In menu edit the first menuitem have the same size than menuitems in mate-panel,
>but other menuitems are smaller.

I did notice when comparing Pluma in 16.04 (GTK2) and 16.10 (GTK3) that the menu width for the **Edit** menu was the same.

**Comment by raveit65** [comment]
> I did notice when comparing Pluma in 16.04 (GTK2) and 16.10 (GTK3) that the menu width for the Edit menu was the same.

Are we talking about height or width ?
I'm talking about different height.

**Comment by lah7** [comment]
For Pluma's edit menu anyway, both the height and width look the same, but I see what you mean:

> I think this depends on size of icons in Ambiant-MATE theme.

**Left:** 16.10, GTK 3
**Right:** 16.04, GTK 2

![screenshot at 2016-05-23 00 11 12](https://cloud.githubusercontent.com/assets/13032135/15457098/19721cc0-207b-11e6-979e-7c291eea69fd.png)

Eww, something's happened to those Undo/Redo icons! :open_mouth:

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/295500edfc2a354c5b1b5e6229eaec1796a6ec8d
This make all kind of menus, ie comboboxes dark.
You can see that with the combobox in transmission window.
Please test.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/57a2b59c8b0be3d5e3d62fbbad9abaa5dbf2dff4
Please test, all gtk3 menuitems should now have the same height.
As the icon size in mate-panel (min 16px) is our limit i increased the height of the other menuitems a bit to make them consistent.
i guess you will ask me to do the same with gtk2 ;)

**Comment by flexiondotorg** [comment]
All looks good to me. @lah7 Please test and report back :-)

@raveit65 If updating GTK2 is not too much hassle please do so :-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f2f27c3599ad8edd72d0668e0b5f8380873214d8
no hassle :)
Hope i matched all menus.
Please test

**Comment by lah7** [comment]
I feel like we've gone a step backwards... The menus are very long (vertically): :-1: 

**Left = GTK3 on 16.10 (latest changes)
Right = GTK2 on 16.04 (ideal size)**

![screenshot at 2016-05-23 16 17 19](https://cloud.githubusercontent.com/assets/13032135/15475442/0ed299d4-2102-11e6-9b3d-ba9d7e938f74.png)

The original issue is that the width in `mate-panel` was much wider then anticipated.

**Comment by flexiondotorg** [comment]
I confirm that GTK2 and GTK3 menus vertical height are restored to how they were previously and acknowledge the width of the panel menus can't be altered via theming.

Thanks for your patience on this one @raveit65 .
