### ISSUE TITLE
GTK2 toolbars are light and GTK3 toolbars are dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#12]
We like the dark toolbars now present in the GTK3 version of the theme. The GTK2 theme should be updated to also use a dark toolbar.

The following bug report includes a patch that should get us most of the way there. 

  * https://bugs.launchpad.net/ubuntu-mate/+bug/1338132

@flexiondotorg will have a first attempt at getting this integrate.

**Comment by raveit65** [comment]
Hmm, with mate-1.16 we switch to gtk3 than all this is history.
Theming gtk2 is a mess because i can't use gtk3-inspector.
So I let the finally left.

**Comment by flexiondotorg** [comment]
This request is so existing GTK2 applications (Gimp, Geany, etc) look more like GTK3.

**Comment by raveit65** [comment]
I will see if i can use settings from Submarine themes, they have dark toolbars in gtk2.

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/c3abfbe7a52a25753aa96abb5d6268e8a3db296a
I tested it with geany but there is a GtkToggleButton on the right hand side of the toolbar which doesn't follow tool-button styling (the dropdown button if you using a small window).
I tried something like this what i found in a old ubuntu TODO, but nothing helps.
```
widget_class "*<GtkToolbar>.*.<Togglebutton>*" style "toolbar-button"
class "*<GtkToolbar>.*.<Togglebutton>*" style "toolbar-button"
widget_class "*<GtkToolbar>.*.<togglebutton>*" style "toolbar-button"
class "*<GtkToolbar>.*.<togglebutton>*" style "toolbar-button" 
```
Sorry, i'm not very good in gtk2 theming and i don't like it very much.
So, this this needs to testing to avoid unwanted colors in some applications.

Btw. i noticed the same issue with my Submarine themes.

**Comment by flexiondotorg** [comment]
The dark tools bars look ugly in LibreOffice, is it possible to always make LibreOffice tool bars light? 

However, GTK2 drop menus (File, Edit, View, etc) have become light when they were previously dark. Can you make the drop menus for GTK2 dark again please? We want that regardless. The submarine themes have dark menus too :-)

Luke and I will test the GTK2 dark tool bars some more before we decide if we want them. But do make the menus dark again in the mean time :-)

**Comment by flexiondotorg** [comment]
The light GTK2 menus has also made menus in Firefox GTK2 and Google Chrome light as well, when they were also previously dark.

**Comment by flexiondotorg** [comment]
Light GTK2 is now resolved. So the decision remain, do we keep dark GTK2 tool bars?

**Comment by lah7** [comment]
### Light
![image](https://cloud.githubusercontent.com/assets/13032135/15456323/66ae955c-2064-11e6-8b18-57305182b188.png)
(From theme originally)

### Dark
![image](https://cloud.githubusercontent.com/assets/13032135/15456325/6c32f6da-2064-11e6-9d02-5cb79d804e8a.png)
(New changes)

Hmm... I like the dark toolbars at the fact this makes it consistent with GTK3 applications, **but** at first sight, the translucent "disabled" buttons are not as easy to see as they once were. In particular, the "Build" button. 

If disabled buttons can be adjusted to be a bit more clearer, that would be good.


----------

**There's also some new bugs:**

At the bottom of this GTK2 load/save dialog:
![image](https://cloud.githubusercontent.com/assets/13032135/15456350/6e1cb6c4-2065-11e6-8e5e-dcc4fea62551.png)

Eye of MATE also seem to have become Frankenstein: 
![image](https://cloud.githubusercontent.com/assets/13032135/15456352/842b650a-2065-11e6-89ea-5c893817a39d.png)

**Comment by raveit65** [comment]
Well, getting any MATE gtk3 to work with dark toolbars is no problem.
But the for the other GTK2 load/save dialog if have no idea.
Theming gtk2 is very limited and this can cause also fallouts in other gtk2 apps.
Taking Submarine themes as reference, i see also issues with them but i still ignore them ;)
Mixing a theme with dark and light elements is not a easy task with gtk2 as it is limited by gtk2.
So again, does this all make sense?
I'm in doubt that it is possible to make a gtk2 theme 100% similar to its gtk3 pedant.

**Comment by lah7** [comment]
As much as I like the idea of keeping it consistent (dark) - going dark is probably not worth it and will only end up with more eyesores. Thanks for the info @raveit65.

So I'm opting to keep with what we've got. What do you say @flexiondotorg?

**Comment by raveit65** [comment]
@lah7 
> If disabled buttons can be adjusted to be a bit more clearer, that would be good.

You can pLay a bit with INSENSITIVE colors in dark color definitions for all states.
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-2.0/gtkrc#L138
and the followers.

**Comment by raveit65** [comment]
fix for eom, atril and possible others.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/97ab9c93973066f817491636b91210c582c1e714
Please test.

**Comment by flexiondotorg** [comment]
I confirm that EOM and Atril are looking good.

@raveit65 Is it possible to address the GTK2 save/load issue and disabled buttons in GTK2 tool bars that @lah7 mentioned earlier?

**Comment by raveit65** [comment]
> Is it possible to address the GTK2 save/load issue and disabled buttons in GTK2 tool bars that mentioned earlier?

Insensitive buttons = yes
The other i don't think i will find a solution, this is the result of that we have in gtk2 only one toolbar class. In gtk3 we have .toolbar, .primary-toolbar and .inline-toolbar.
What you see here is a inline-toolbar with GTK3.
So, i have no chance to style that toolbar with another setting without matching all toolbars.

PS: with submarine themes i have the same dark toolbar in GTK2 save/load dialog.
But never someone bother me about that.

**Comment by raveit65** [comment]
insensitive colors are lighten up as requested fot GTK2.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/8ae11a576dda01ce8220a779a4ff2cd4d3a302ae

**Comment by lah7** [comment]
Thanks -- It seems to have only lightened the drop down arrows (e.g. open / build) but the icons remain the same opacity?

### New
![image](https://cloud.githubusercontent.com/assets/13032135/15481783/3138bc02-2124-11e6-8e4e-33fc0c036c1f.png)

### Previous
![image](https://cloud.githubusercontent.com/assets/13032135/15456325/6c32f6da-2064-11e6-9d02-5cb79d804e8a.png)

**Comment by raveit65** [comment]
Check you icon theme.
Do you think that a icon theme for a light theme works on dark backgrounds?
I consider to use icons from mate-faenza-dark.

**Comment by flexiondotorg** [comment]
I consider this issue closed now.
