### ISSUE TITLE
Inactive tabs in GTK3 and not fully drawn

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#13]
See the screen shots below for a comparison between GTK2 and GTK3. Would prefer the GTK3 tabs are more like GTK2 where the inactive tabs are completely drawn.

## GTK2

![tabs_gtk2](https://cloud.githubusercontent.com/assets/304639/15403235/ebd1f714-1def-11e6-8e9b-b9cf43368698.png)

## GTK3

![tabs_gtk3](https://cloud.githubusercontent.com/assets/304639/15403246/f3f7171c-1def-11e6-855c-bd4400bad59e.png)

**Comment by raveit65** [comment]
wtf, gtk3-widget-factory shows me that notebooks doesn't have any styling

**Comment by raveit65** [comment]
please test
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e75323bf186fdfaf4c7add8a352330eb8b05871b

**Comment by flexiondotorg** [comment]
Excellent! I confirm this issue is fixed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9d30f556023a0c696ae2bac4c6e23496b4b946cc
