### ISSUE TITLE
Reduce horizontal padding in GTK3 toolbars.

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#14]
As mentioned in chat, the items in toolbars have a lot of spacing, causing items to start hiding when the window is small.

#### Caja
![image](https://cloud.githubusercontent.com/assets/13032135/15403413/c3981142-1df0-11e6-9395-c648d52db054.png)
![image](https://cloud.githubusercontent.com/assets/13032135/15403421/c793e794-1df0-11e6-8c2e-aec71693fc06.png)

#### Pluma
![image](https://cloud.githubusercontent.com/assets/13032135/15403431/cf1bf380-1df0-11e6-98da-74af10fcd422.png)
![image](https://cloud.githubusercontent.com/assets/13032135/15403434/d08aeb7c-1df0-11e6-807d-2a040f26a658.png)

**Comment by raveit65** [comment]
well, someone added a padding of 9px to gtk3 :smile: 
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L1723

**Comment by raveit65** [comment]
Is this size better?
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/1cc22fec0fd4f244188199d2569c7791c0b590c8

**Comment by flexiondotorg** [comment]
Looks much better to me. I'm inclined to close this as fixed, but will wait for @lah7 to comment :-)

**Comment by lah7** [comment]
That's better thanks -- now a bit too squished I think, how an extra pixel or two of padding?

![image](https://cloud.githubusercontent.com/assets/13032135/15430682/514fc0d6-1e9e-11e6-9fc2-25d80a7261f0.png)
![image](https://cloud.githubusercontent.com/assets/13032135/15430686/525ae870-1e9e-11e6-97e5-693ee62aedff.png)

**Comment by raveit65** [comment]
In which direction (horizontal or vertical) you wanna have 1or 2 pixel?
Btw. i think i's easier and quicker testing this for your own.
Play around with
    padding: 3px 3px;     (vertical/horizontal)
at https://github.com/flexiondotorg/ubuntu-mate-themes/blob/1cc22fec0fd4f244188199d2569c7791c0b590c8/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L1723

**Comment by flexiondotorg** [comment]
@lah7 I've just had a play and bumped the primary toolbar padding to 6px. Thoughts? I think it looks about right. ef8ab716bc39c77b7d7a9e1fc63329925e3326cf

**Comment by lah7** [comment]
Set to 5px and I think we have a winner:

### 5px
![image](https://cloud.githubusercontent.com/assets/13032135/15434441/c5a863f6-1eae-11e6-9c17-7b0fd17c51f5.png)

![image](https://cloud.githubusercontent.com/assets/13032135/15434443/c7486d3c-1eae-11e6-93a5-87a4192cfd87.png)

### 6px
![image](https://cloud.githubusercontent.com/assets/13032135/15434499/09cb783e-1eaf-11e6-8222-6ba0fe8e488e.png)

![image](https://cloud.githubusercontent.com/assets/13032135/15434503/0bf4bdfa-1eaf-11e6-8570-a01ff57cff8b.png)

**Comment by raveit65** [comment]
done for Radiant theme
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/c0db737a49bb5fd144149b3baa80334bed8eea3b
