### ISSUE TITLE
GTK3 tabs are wider than GTK2

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#15]
As seen here in Pluma, the tabs <strike>put on some weight</strike> are much wider then it's GTK2 counterpart.

### GTK3
![upload](https://cloud.githubusercontent.com/assets/13032135/15406109/ea68442a-1dfc-11e6-861a-3196973950bf.png)

### GTK2
![upload 1](https://cloud.githubusercontent.com/assets/13032135/15406115/eeedd582-1dfc-11e6-8706-8d9e8eb5f486.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e75323bf186fdfaf4c7add8a352330eb8b05871b

**Comment by flexiondotorg** [comment]
Great. I confirm this is fixed :-)

**Comment by lah7** [comment]
To compare the new changes, I would have suggested an extra pixel or two of padding - since it looks a tad bit condensed.

![image](https://cloud.githubusercontent.com/assets/13032135/15477762/6a94cf88-210e-11e6-9a07-2ca8cd733548.png)
![image](https://cloud.githubusercontent.com/assets/13032135/15406115/eeedd582-1dfc-11e6-8706-8d9e8eb5f486.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/1177a93f5e6c2e1ba83fe2f58b461f1cd83009d8
