### ISSUE TITLE
Dark sidebar for Caja

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#16]
As discussed yesterday in chat, it would be desirable if the side bar colour in Caja to a darker colour, similar to Nemo (another fork of Nautilus, which is GTK 3).

### Caja
![caja](https://cloud.githubusercontent.com/assets/13032135/15427435/0afacd12-1e8d-11e6-93fc-ca5a1da42d00.png)
(Nicking @flexiondotorg's screenshot :wink:)

### Nemo
![nemo](https://cloud.githubusercontent.com/assets/13032135/15427440/0dcde196-1e8d-11e6-946f-21b427c57abd.png)

(Old screenshot of mine with blue theme/icons)

**Comment by raveit65** [comment]
Hmm, here caja, nemo and nautilus have the same sidebar color, a little bit darker than bg color of view.
![bildschirmfoto zu 2016-05-20 15-34-10](https://cloud.githubusercontent.com/assets/961604/15429322/ae421652-1ea0-11e6-9c85-16456ed4ff9c.png)
But i can switch to a darker color for all browser if you like,
.......but which color?   :smile:

**Comment by lah7** [comment]
Nautilus' colour of `#F2F1F0` (242, 241, 240) please.

The dark side bar will have to come from another theme instead. :ok_hand: Or study how this works and modify themes myself. :wink:

**Comment by flexiondotorg** [comment]
@raveit65 Yep, I agree with @lah7 `#F2F1F0` please :-)

**Comment by raveit65** [comment]
Hmm digging deeper shows me that nautilus use the bg color of the theme :smile: 
Setting none bg here https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L538
means that the bg of the theme is used.
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-main.css#L2
This might be OK for a CSD app like nautilus, but looks quite worse for caja or nemo.
Because than sidebar color is the same like places toolbar.
Do you really want this?
I will make a suggestion for you.

**Comment by flexiondotorg** [comment]
@raveit65 This is not high priority/essential. So move on to something else, but I'd be interested to hear your suggestion :-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/816b0b73796c60b6def75a0df989a7ac73e4893e
I used 
```
background-color: shade (@bg_color, 0.98)
```
 or
```
 #EEEDEB
```
for caja. this a bit darker than the theme bg color.
If you like it i will adjust the color for nautilus, nemo and filechooser sidebar.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/2488523903fe7a677a018b172c4cc28e1b36edd1

**Comment by lah7** [comment]
That's looking nicer! :+1:

![image](https://cloud.githubusercontent.com/assets/13032135/15441214/91ec7fd4-1ed1-11e6-88a0-dcb8ac3f12bf.png)

**Comment by flexiondotorg** [comment]
@raveit65 Yes, much improved. Thanks. We'll take that as fixed :-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3ff1fd130447ca364d7253f38c4ffac56635f9dd
I added a dummy setting which set all sidbars to white.
You can change the color if needed.
The only setting for sidebars was for the gtk3 filechooser.
background-color: shade (@bg_color, 0.95);
This would make the sidebars a bit darker than the bg color.
