### ISSUE TITLE
Ambiant-MATE theme broken in LibreOffice

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#17]
As reported here: https://bugs.launchpad.net/ubuntu-mate/+bug/1550990

> LibreOffice pulls a particular color reference from the desktop theme and uses it in various places and it seems the particular color it pulls from the default Ambiant-MATE likely isnt set, as LibreOffice is using black in those areas. This doesnt happen with other bundled themes like Blue-Submarine, High Contrast, Menta, Radiant-MATE, TraditionalGreen, and Yuyo. The only other bundled theme where this issue arises is in GreenLaguna.
> 
> The attached screenshot has red square around the areas that are affected by this selected color.

![libreoffice color](https://cloud.githubusercontent.com/assets/13032135/15451024/dbc925b8-1fa7-11e6-9993-a904a08b6c98.png)

--------------
> ... there also are some artefacts with checkboxes (checked and unchecked).
The only themes without this problems are Green-submarine, Blue-submarine and the two contrast-themes.
>
>Please see my screenshot.
>Using Ubuntu MATE 15.10, 64 bit and LibreOffice Version: 5.0.5.2

![lo_theme_broken](https://cloud.githubusercontent.com/assets/13032135/15451025/dbcca51c-1fa7-11e6-963e-33ba0532bfec.png)

**Comment by raveit65** [comment]
if you mean Libreoffice gtk3.....for get it :)
Libreoffice and and firefox gtk3 don't use gtkwidgets and do a lot of hardcoding stuff.
For this reason it is is impossible to use gtk3-inspector, in result theming is try&error and burn a lot of hours.

**Comment by raveit65** [comment]
Tthis is the explanation from gtk+ dev M.Clasen why we can't use gtk3-inspector for firefox and libreoffice.
```
<mclasen> raveit: GDK_BACKEND=x11 GTK_DEBUG=interactive firefox works here
<raveit65> mclasen, yes that works, but i can only select the main frame 'window.background widget'
<mclasen> raveit65: the toplevel may be all there is... firefox is not generally using gtk widgets, it just uses gtk for drawing
```
Sorry, libreoffice and firefox don't want that someone fix issues.

**Comment by flexiondotorg** [comment]
No, don't mean GTK3. LibreOffice seems to "inherit" some widget styling from GTK, possibly GTK2 but I'm not sure. The first screenshot shows black is used but you `mate-themes` use colours from the theme. I did look into this a while back and found a "mubuntu" theme on the MATE forums that partially addressed this issue.

**Comment by raveit65** [comment]
I can't reproduce the issue with checkboxes.
![bildschirmfoto zu 2016-05-22 15-18-08](https://cloud.githubusercontent.com/assets/961604/15454174/b695491e-2030-11e6-8b10-b4e0a0955a5d.png)

Btw. maybe this is the result of some performance fixes
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/c7bc35b66c880272e8cb039da3ec6d67d691c8b7
Please test :)

**Comment by flexiondotorg** [comment]
I confirm that I can not reproduce the checkbox issue either :-)

Excellent work on the LibreOffice fixes, I confirm you've nailed it.

**Comment by flexiondotorg** [comment]
While the commit did correct LibreOffice it had the side effect of making all GTK2 drop down menus light, rather than dark. We've decided to dodge trying to fix LibreOffice, which doesn't adhere to GTK2 standards, and wait patiently for a GTK3 build to land in Ubuntu instead :wink:
