### ISSUE TITLE
Workspace applet has a gradient when applications are present

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#18]
The Workspace switcher applet has gradients when and application is present in a workspace. Please remove the gradients.

**Comment by raveit65** [comment]
Is there a reason why you don't like modern styling?    :P

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/d36b3c9203c2d55d7edafe8e8dd1f198f7647a71

**Comment by flexiondotorg** [comment]
Not all change is progress :stuck_out_tongue: 

I confirm that the workspace applet is beautifully flat again :smile:
