### ISSUE TITLE
Double ringed highlighted buttons

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#19]
Some buttons when "highlighted" have a double ring, as shown in the Find button in the included screenshot. Can that double ring be replaced with a simple green highlight like most other buttons?

![button_highlight](https://cloud.githubusercontent.com/assets/304639/15472940/7b24efe0-20f5-11e6-8c7e-331e8d9cc251.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/0983dd168a19668c525564cd772c90fe1c7081c5
done :)

**Comment by flexiondotorg** [comment]
Much better :-)

That button is the default "action", can it have a green highlight?

**Comment by raveit65** [comment]
better?
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/bf1fe1f0a5194bb740bb54a09c5e2ab6fe05c81c

**Comment by flexiondotorg** [comment]
Close enough :-) It looks much cleaner now.

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/d742376d2f762cb8ea0c7b8f4233a06d5c3c74c9
