### ISSUE TITLE
Applications in the window switcher have incorrect highlight in GTK3

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#2]
Please see the attached screenshots. The active applications have a light highlight in the window switcher on MATE 1.14 built against GTK3. The highlighting for inactive application is also incorrect, dark font and no border.

# Active applications

## GTK2

![window_switcher_active_gtk2](https://cloud.githubusercontent.com/assets/304639/15396618/c56814ca-1dd4-11e6-8358-1c20df2e595d.png)

## GTK3

![window_switcher_active_gtk3](https://cloud.githubusercontent.com/assets/304639/15396639/d82dfeda-1dd4-11e6-86df-a2b2631ea046.png)

# Inactive applications

## GTK2

![window_switcher_inactive_gtk2](https://cloud.githubusercontent.com/assets/304639/15396742/52478c86-1dd5-11e6-84e6-c5a34961b7b1.png)

## GTK3

![window_switcher_inactive_gtk3](https://cloud.githubusercontent.com/assets/304639/15396753/5e2b317e-1dd5-11e6-8682-6c13e887b0cb.png)

**Comment by raveit65** [comment]
yeah, all button in panel use the wrong settings for checked/hover/hover:active state.
I will add a complete setting for mate-panel.

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3d5ea5b05acd4f1e82b44aed7d28bc0b19490633

**Comment by flexiondotorg** [comment]
I confirm this is fixed :-)
