### ISSUE TITLE
Some control buttons clip each other

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#20]
Some control buttons clip each other, then can be seen in the attached screenshots from Disks. I've seen that same issue in Ubiquity (the Ubuntu installer) except the icons used there are smaller.

![disk_controls](https://cloud.githubusercontent.com/assets/304639/15477543/0d990854-210d-11e6-8fbe-36d8dc304416.png)

![disk_controls_2](https://cloud.githubusercontent.com/assets/304639/15477548/115e90bc-210d-11e6-90b9-da459432089a.png)

**Comment by raveit65** [comment]
fixed
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/2a250057c63e9b03ac510bf5938788c166af1d24

**Comment by flexiondotorg** [comment]
Thank you. I confirm that is fixed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/66df439020d48f96fb5cafd0266065be33c19b9e
