### ISSUE TITLE
Icon and text "too close" on buttons

### ISSUE THREAD

**Issue by lah7** [flexiondotorg/ubuntu-mate-themes#21]
A tiny 1px of margin or padding is required on buttons between the icon and the text.

### GTK3
![image](https://cloud.githubusercontent.com/assets/13032135/15477594/4dae0cc8-210d-11e6-9d9d-fc72a9c0ce09.png)

![image](https://cloud.githubusercontent.com/assets/13032135/15477595/4ef27010-210d-11e6-8d12-a7a766725e87.png)

### GTK2
![image](https://cloud.githubusercontent.com/assets/13032135/15477609/65b661b2-210d-11e6-8ef4-5ff6d4ce2320.png)

![image](https://cloud.githubusercontent.com/assets/13032135/15477606/642d766e-210d-11e6-918b-577ec2eb8915.png)

**Comment by raveit65** [comment]
than fix it :)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/038bf395f2e6ce84cd1fd64d8fd190deb276a662

**Comment by flexiondotorg** [comment]
Thank you. Confirmed fixed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f60a02b431f35081f4f38cf0dc5eb038028a7f4d
