### ISSUE TITLE
Calendar applet requires Menta-like theme

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#22]
When the Calendar applet has been clicked it is mostly plain white. Can you please apply the same styling used by Menta but use the Ubuntu MATE green for the highlighting :-)

**Comment by raveit65** [comment]
np,
but one question...
Do you expect from me a complete re-work of the theme?
I have the feeling that with every issue i have fixed you guys open 2 new ones.

**Comment by flexiondotorg** [comment]
No, not a complete rework :-) The issues we've raised are to restore in the GTK3 theme what was previously in the GTK2, plus a couple of tweaks. I think the remaining issues get to the point for Ambiance-MATE.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/102cebfd11606f4571289c1ad3292e983215708f

**Comment by flexiondotorg** [comment]
I confirm this is fixed. Looks brilliant in fact :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/80b6f8a378e19d0ed31d91f0d09c3bcc86d404d9
