### ISSUE TITLE
Volume applet is a light but should be dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#23]
When the volume applet is clicked the volume slider is light but should be dark. The "runner" is great, as is the marker, but the background should be dark :-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f72a1deaeec6b82610a968f9f809a24b29475ad7

**Comment by flexiondotorg** [comment]
I confirm that fixed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f60a02b431f35081f4f38cf0dc5eb038028a7f4d

**Comment by raveit65** [comment]
opps, wrong commit

**Comment by raveit65** [comment]
for radiant theme
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/caffe9ad304a85595945aeaf75cb13bddeff39d8
