### ISSUE TITLE
Eye of MATE toolbar is incorrectly themed

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#24]
The toolbar in Eye of MATE doesn't match the other Ambiant-MATE themed applications. See the attached image.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE only.

![eom theming looks incorrect](https://cloud.githubusercontent.com/assets/304639/18435174/9bba6d38-78e9-11e6-8e8d-0f7fb4aadeb3.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/44907bd10eb80c31c2d7595c50b79b5198b872d1

**Comment by flexiondotorg** [comment]
Tested. I confirm this fixes the issue. Thank you :-)
