### ISSUE TITLE
Atril toolbar is incorrectly themed

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#25]
The toolbar in Atril doesn't match the other Ambiant-MATE themed applications. See the attached image.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE only

![atril theming looks incorrect](https://cloud.githubusercontent.com/assets/304639/18435217/d86ac39a-78e9-11e6-831d-fceb411c8f80.png)

**Comment by raveit65** [comment]
Please test.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/44907bd10eb80c31c2d7595c50b79b5198b872d1

**Comment by flexiondotorg** [comment]
Tested. I confirm this fixes the issue. Thank you :-)
