### ISSUE TITLE
Lock screen is not correctly themed

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#26]
See the attached screenshot.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

![lock screen is not themed](https://cloud.githubusercontent.com/assets/304639/18435313/489fa900-78ea-11e6-8d61-0ea4ef64c75b.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3fb6f1eb919d6413fe4c548793ac58aa4a9d097a

Note, this commit is needed from m-s.
https://github.com/mate-desktop/mate-screensaver/commit/e3d8ca494335bcea1aa776614ed17c75012e1f2b

**Comment by flexiondotorg** [comment]
I've tested and confirm it is fixed :-)
