### ISSUE TITLE
Text on tabs is light when it should be dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#27]
See that attached screen shot for a caparison of tabs in GTK3 (Pluma) and GTK2 (Geany). The text on the GTK3 is light, it should be dark as shown in Geany.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

![text on tabs in gtk3 applications is light](https://cloud.githubusercontent.com/assets/304639/18435365/891891a4-78ea-11e6-9d8a-8925113ba6d5.png)

**Comment by raveit65** [comment]
Please test.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f8b4a3b1bf54dd0ebf84b720a37aa82125474b9d

**Comment by flexiondotorg** [comment]
Tested. Confirming it is fixed. Thanks :-)
