### ISSUE TITLE
Applet menus are too condensed in Ambiant-MATE

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#28]
The applet menus items are too squashed when using Ambiant-MATE. However, **the spacing is correct is Radiant-MATE**. Please apply the same spacing to Ambiant-MATE as used in Radiant-MATE. See the screen shot below.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE only
  * Only the vertical spacing/padding needs to be addressed

![applet menus gtk3 crop](https://cloud.githubusercontent.com/assets/304639/18435677/9cfdf45a-78ec-11e6-839e-46efedc34e0e.png)

For comparison, this is how they look in GTK2.

![applet menus gtk2 crop](https://cloud.githubusercontent.com/assets/304639/18435681/a159920c-78ec-11e6-8df1-78dc0b566a4f.png)

**Comment by raveit65** [comment]
hmm, auto-closed if i add issue link in commit body :)

For me it looks now equal with Ambiant and Radiant theme.

**Comment by flexiondotorg** [comment]
I've just tested this. Thanks, looks much better :-)
