### ISSUE TITLE
Outlines where there should be none

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#29]
Some applications now has outline in parts of the UI where previously there were none. This is best seen in the System tab of MATE System Monitor, but can also be seen in several other applications suchas Sound Preferences and MATE Tweak. **Green Submarine does not exhibit the issue**.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

![outlines in ambiant-mate](https://cloud.githubusercontent.com/assets/304639/18435813/37e67f96-78ed-11e6-9abe-618b57d9dd4a.png)

For comparison here is the same screenshot using Green Submarine.

![outlines not in green submarine](https://cloud.githubusercontent.com/assets/304639/18435838/568321ca-78ed-11e6-9129-329f3c23f610.png)

**Comment by raveit65** [comment]
Borders on frame is one of the side effect of using nodes with gtk+-3.20.
A frame is everywhere in in widget hierarchy.
Let's eliminate them.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/5aae94c5a7b16d151a341a81655f1b65f86816ed
Hope, i matched everything and didn't remove borders where they belongs. 

Offtopic on:
Hmm, looks there is something broken with GS panel styling.
Offtopic off.

**Comment by flexiondotorg** [comment]
I've tested this and confirm it resolves the issue in all the places I found it with no regressions :-) Thanks and Closed.
