### ISSUE TITLE
Terminal is incorrectly themed in GTK3

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#3]
The `mate-terminal` background colour and font colour are incorrect in MATE 1.14 build against GTK3. See the screen shots for a comparison with GTK2.

## GTK2

![mate-terminal-gtk2](https://cloud.githubusercontent.com/assets/304639/15396970/4e1ccf3a-1dd6-11e6-802f-757e7f5c8f80.png)

## GTK3

![mate-terminal-gtk3](https://cloud.githubusercontent.com/assets/304639/15396979/54ec53a8-1dd6-11e6-8a42-96924bb5f8af.png)

**Comment by raveit65** [comment]
Setting the terminal color is a easy task.

**Comment by raveit65** [comment]
Hmm, weird,
here i have a white background if i choose 'use theme settings' in preferences.

**Comment by raveit65** [comment]
Ok, mate-terminal use settings for gnome-terminal :smile:

**Comment by raveit65** [comment]
Please test, this should fix the issue.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3456f45f9a65fed9cbf5d50187003e93c5e9846e

**Comment by flexiondotorg** [comment]
I confirm that is fixed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
hope this is the right color for Radiant theme.
.....for some reason i see only a white bg :)
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/980886a1f8eb5354e9c538798c3c77132e541061
