### ISSUE TITLE
OSD is green with green volume bar

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#30]
The OSD is green and the volume bar is also a similar shade of green. Please can you make the OSD background colour a share of gray that matches the relevant theme. Although the colours wouldn't match, the BlackMATE OSD style looks a good candidate.

See the screenshot below.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE.

![osd is green](https://cloud.githubusercontent.com/assets/304639/18505091/81740dc4-7a5d-11e6-8aca-65560e70327f.png)

**Comment by raveit65** [comment]
Please test.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3eed1472318922115c5dac3cf4509f343242757a
Not sure about Radiant theme. Looks like we need icons from Ambiant theme here

**Comment by flexiondotorg** [comment]
Tested. Much better, thank you :-)
