### ISSUE TITLE
Firefox Tooltips are dark text on black background

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#31]
As seen in the attached screenshot, Firefox tooltips are dark grey text on a black background. Please can the text be made white like the other tooltips. **This issue doesn't affect BlackMATE, so there must be a fix in there somewhere** :-)

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Firefox 48.0
  * Affects Ambiant-MATE and Radiant-MATE

![firefoxtooltips](https://cloud.githubusercontent.com/assets/304639/18505828/edf2acbe-7a60-11e6-845f-32dc867bba95.png)

**Comment by raveit65** [comment]
Hmm, fonts are looking a bit ugly here, but color is white on black.
![bildschirmfoto zu 2016-09-14_13-47-59](https://cloud.githubusercontent.com/assets/961604/18511138/65d43664-7a82-11e6-8db0-297bb981f1e5.png)

firefox version is 48.0.1
.....i hate theming firefox gtk3....

**Comment by raveit65** [comment]
Please test.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3b243e3994cd41cb188f1da7af87c8817daddcfb

**Comment by flexiondotorg** [comment]
Nicely done! Thanks, that works a treat :-)
