### ISSUE TITLE
LightDM Login Dialogue is transparent

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#32]
As seen in the attached screenshot, LightDM login dialogue is now transparent. This may have been introduced around the time the lock screen theme was fixed, but I'm not certain.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * `lightdm` 1.19.4 and `lightdm-gtk-greeter` 2.0.1
  * Affects Ambiant-MATE and Radiant-MATE

![lightdm transparent](https://cloud.githubusercontent.com/assets/304639/18508693/133d5256-7a6d-11e6-811d-bba743b29c92.png)

**Comment by raveit65** [comment]
Please test!
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9970206ac09146be2b18d0996ebb304a3c308336

**Comment by raveit65** [comment]
Btw. probably the issue is caused by this change https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f98dc2f4111c4b910eda517e4d4a79779a9c7e73
It is important to know why it happened.

**Comment by flexiondotorg** [comment]
OK, so that fixes the login dialogue, but the Shutdown and Restart dialogues still exhibit the issue.

![lightdm_restart](https://cloud.githubusercontent.com/assets/304639/18543036/b6d9445c-7b25-11e6-81bc-60455468a5e6.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9dda1220423eca62c67d3089593e1702bf85f210
Please test again :)

**Comment by flexiondotorg** [comment]
That's got it :-)
