### ISSUE TITLE
Ubiquity background is white

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#33]
As seen in the attatched screen shots the background of Ubiquity windows is `#ffffff`but it should be darker.

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

## Ambiant-MATE

![ubiquity_001](https://cloud.githubusercontent.com/assets/304639/18509086/c994a274-7a6e-11e6-9a2a-02c68324e2f8.png)

![ubiquity_002](https://cloud.githubusercontent.com/assets/304639/18509087/c995cf64-7a6e-11e6-9598-da6b674fc455.png)

![ubiquity_003](https://cloud.githubusercontent.com/assets/304639/18509088/c9a41060-7a6e-11e6-9bfe-fa89f635d502.png)

## Ambiance

For comparison this is how Ubiquity looks using Ambiance (Ubuntu default theme).

![ambiance_ubiquity_001](https://cloud.githubusercontent.com/assets/304639/18509211/5a3588de-7a6f-11e6-965f-ecae88535340.png)

![ambiance_ubiquity_002](https://cloud.githubusercontent.com/assets/304639/18509212/5a35d532-7a6f-11e6-8085-dda6eb9538a0.png)

![ambiance_ubiquity_003](https://cloud.githubusercontent.com/assets/304639/18509214/5a4ac956-7a6f-11e6-9c4a-6066caa3e809.png)

In order to test this you'll need an Ubuntu MATE 16.10 VM, get the iso here:

  * http://cdimage.ubuntu.com/ubuntu-mate/daily-live/current/

If you already have Ubuntu MATE 16.10 installed in a VM you can install Ubiquity and execute it:

    sudo apt install ubiquity-frontend-gtk

Once installed it can be launched by running `ubiquity` from a terminal or via *System -> Administration -> Install RELEASE*.

While running Ubiquity on an installed system say **No** to unmounting `/dev/sda` and to see the partition setup choose **Something else** for the *Installation type*. Obviously don't actually try an install on an installed system ;-)

**Comment by raveit65** [comment]
Please test
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e58af79999d9f0db11d0fd4d52d29d2e16f3c669

**Comment by flexiondotorg** [comment]
Sadly, I don't see any difference :-(

**Comment by raveit65** [comment]
weird, here ubiquty looks like this now.
![bildschirmfoto zu 2016-09-15_13-40-09](https://cloud.githubusercontent.com/assets/961604/18548637/1dbc4a56-7b4a-11e6-923d-0710c535a65c.png)

**Comment by flexiondotorg** [comment]
Your screen shot is also not correct, the Ubiquity background is white. It should look like this:

![ambiance_ubiquity_001](https://cloud.githubusercontent.com/assets/304639/18509211/5a3588de-7a6f-11e6-965f-ecae88535340.png)

**Comment by raveit65** [comment]
But my screenshot shows a white bg with 2 large dark stripes on top and bottom.
What is the different to your screenshot?

**Comment by flexiondotorg** [comment]
Right, yes. You have reinstated the dark header/footer. I completely missed that. Great.

**Comment by flexiondotorg** [comment]
Hopefully this helps explain.

![mix](https://cloud.githubusercontent.com/assets/304639/18550217/9e660282-7b4a-11e6-9d06-2ff75ddb4dcc.png)

**Comment by raveit65** [comment]
Please test again.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/c1d7522dbdff8be734d5779c6919e0a481676be0

**Comment by flexiondotorg** [comment]
I've completed a full install using this update. All good, thanks! :-)
