### ISSUE TITLE
MATE Menu theme is too funky ;-)

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#34]
The Ambiant-MATE theme for MATE Menu is a bit too fancy and the Radiant-MATE theme needs a  little tweaking.

## Issues affecting Ambiant-MATE and Radient-MATE

  * The items in the Applications Categories are not vertically tall enough and when hovered "pop" to the correct size.
    * The items in the Applications Categories should be the correct vertical size and not "pop" when hovered.
  * The Application items are bit too vertically condensed.
    * Please space them out like in the Radience comparison screenshot.
  * Items should be flat and only display and button outline when hovered, as in the Radience comparison screenshot.

## Issues affecting Ambiant-MATE only

  * Everything is a button with a gradient.
    * Items should be flat and only display and button outline when hovered, as in the Radience comparison screenshot.
  * There are borders around various elements.
    * Those borders should be removed, as in the Radience comparison screenshot.
  * Scrollbar theme is not a consistent with the rest of the theme.

## Issues affecting Radiant-MATE only

  * The menu background is white.
    * The background should be `#EEE9E4`.

### Ambiant-MATE

![mate-menu-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/18545690/1c15d39c-7b32-11e6-9e71-8aabc357efb8.png)

### Radience

For comparison, **this is the Ubuntu Radience theme, not Radiant-MATE.** You can Radience with `sudo apt install light-themes`.

![mate-menu-radience](https://cloud.githubusercontent.com/assets/304639/18545711/388d7b9c-7b32-11e6-8306-3eb85a9f1671.png)

  * Running latest MATE 1.15.x tarballs and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

**Comment by raveit65** [comment]
for Ambiant theme: https://github.com/flexiondotorg/ubuntu-mate-themes/commit/22dec87eddfdcde4d98e47e2e68c86dbb2fd0627
> Scrollbar theme is not a consistent with the rest of the theme.

Do you really want a light scrollbar styling on a dark background?

**Comment by raveit65** [comment]
for Radiant: https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7deea4c8ce4c1bfbb5db4cae579532174c02447b

**Comment by flexiondotorg** [comment]
Perfect! Thanks you :-)
