### ISSUE TITLE
Missing arrow for expandable terminal

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#36]
As seen in the attached screen shots their is an arrow symbol missing, just in front of the word *Details*, that indicates that an terminal view can be expanded/collapsed. This can be reproduced by installing anything via the Software Boutique or using the Update Manager.

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

![no_embedded_terminal_expose_arrow](https://cloud.githubusercontent.com/assets/304639/19096306/4126cc66-8a93-11e6-9bb0-5ce7e4873e72.png)

**Comment by raveit65** [comment]
Arrows are missing in other apps too, eg. polkit window, caja file override warning window.
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7423fc8bc1a0f11231e163d0dd7846f4197c07da

**Comment by flexiondotorg** [comment]
Excellent. Confirmed fixed. Thanks :-)
