### ISSUE TITLE
Transmission progress bars are not the correct colours

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#37]
As seen in the attached screen shots the Transmission progress bars are not the correct colours.

The progress bar is white when the torrent it's not selected (fist pic), green when it's selected (second pic) but the progress bar will have the same colour no matter how much the download has progressed (third pic)

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

## Not selected

![screenshot_mate-16 10-beta_2016-09-17_00-48-40](https://cloud.githubusercontent.com/assets/304639/19096401/0d45a7cc-8a94-11e6-8642-64a689fc9c26.png)

## Selected

![screenshot_mate-16 10-beta_2016-09-17_00-48-49](https://cloud.githubusercontent.com/assets/304639/19096418/255cfc2a-8a94-11e6-8d09-3017dd60ffb6.png)

## Progress

![screenshot_mate-16 10-beta_2016-09-17_00-50-19](https://cloud.githubusercontent.com/assets/304639/19096435/43f249e2-8a94-11e6-8830-34aa70082955.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/55c2c515ccfb3a5480b9c3a66d03ce11bbcdcc05

**Comment by flexiondotorg** [comment]
I confirm this fixes the issue. Thanks :-)
