### ISSUE TITLE
Artefacts left on Back/Forward buttons in Yelp

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#38]
As seen in the attached screen shot when using the back button in Yelp, small squares remain as artefacts on the button after click back and then remaining hovering over it. **This only affects Ambiant-MATE**.

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE only

*When this screenshot was taken both the back and forward buttons were affected but I can only reproduce with the back button now*

![screenshot_mate-16 10-beta_2016-09-17_01-57-07](https://cloud.githubusercontent.com/assets/304639/19096556/4655c9ba-8a95-11e6-9ef0-0e1cc477ee1c.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/a072c63e7c19acad66414452cc4a6298545388f1

**Comment by flexiondotorg** [comment]
Confirmed fixed, thank you! :-)
