### ISSUE TITLE
Indicators are shown on a solid background when the panel is transparent

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#39]
As seen in the attached screen shot when the panel is transparent the Indicators are still shown on a solid background. **This only affects Ambiant-MATE.**

To recreate this issue you'll need to use Ubuntu MATE 16.10 daily with all updates applied. Then use MATE Tweak to *Enable Indicators* and make the panel transparent. This discussion looks useful:

  * https://github.com/mate-desktop/mate-indicator-applet/issues/17#issuecomment-240700161

Most themes from `mate-themes` 3.20.12 behave correctly although Tradional OK and Tradition Green exhibit the same issue. 

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * *Affects Ambiant-MATE only*

## Ambiant-MATE (incorrect)

![transparent_ambiant_mate](https://cloud.githubusercontent.com/assets/304639/19131305/dc7ada1e-8b46-11e6-8104-d9101c64f2a0.png)

## Radiant-MATE (correct)

![transparent_radiant_mate](https://cloud.githubusercontent.com/assets/304639/19131314/e5020ca2-8b46-11e6-900c-e2eb2d96ccb5.png)

# mate-themes

For reference he are some screen shots from `mate-themes` 3.20.12.

## Black MATE (correct)

![transparent_black_mate](https://cloud.githubusercontent.com/assets/304639/19131354/01c7e8d4-8b47-11e6-97a8-3178a6512c1a.png)

## Traditional Green

![transparent_traditional_green](https://cloud.githubusercontent.com/assets/304639/19131426/4cff661a-8b47-11e6-9b3d-2f50785d0965.png)

## Traditional OK

![transparent_traditional_ok](https://cloud.githubusercontent.com/assets/304639/19131436/51bc669e-8b47-11e6-9b34-0eb692374d58.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/33547279053ca8f98b107fe0dd586010f99fff11

**Comment by flexiondotorg** [comment]
Yep, that works great. Thanks :-)

**Comment by monsta** [comment]
Confirmed, latest ```ubuntu-mate-themes``` update in Ubuntu 16.10 fixed that for Ambiant-MATE here, thanks @raveit65 :smile:
