### ISSUE TITLE
Some GTK3 progress bars have white centres.

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#4]
Some progress bars, Transmission and Update Manager, have white centres. The screen shots below show the affected progress bars and also the unaffected progress bars.

![progressbars_gtk3](https://cloud.githubusercontent.com/assets/304639/15399140/692bf03c-1dde-11e6-8807-6240a610d6c2.png)

**Comment by raveit65** [comment]
Ohh je, i never saw such a shit :)

**Comment by flexiondotorg** [comment]
Started happening in GTK 3.18.

**Comment by raveit65** [comment]
Please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/42575a12e1cbcb1da479ef09821eee9e4724a8c4
Honestly, using the syntax border-image is complete wrong :smile:

**Comment by flexiondotorg** [comment]
I confirm that Transmission is fixed, but the progress of downloads in the Update Manager (or anything that uses aptdaemon-gtk3) still have white centres. See under the *Details* in the "Installing packages" window in the screenshot above.

**Comment by flexiondotorg** [comment]
I've also noticed Transmission progress bars have white centres when transmission is not the active window.

![transmission inactive](https://cloud.githubusercontent.com/assets/304639/15455383/5a81beb8-204a-11e6-9592-b259a8d30838.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3a8f6865c79f630fcda822e2ff17d01f01a1cc6d
Does this fix transmission backdrop state?
As i don't have apt stuff installed i need your help.

**Comment by flexiondotorg** [comment]
@raveit65 I confirm that Transmission is fixed.

**Comment by raveit65** [comment]
@flexiondotorg still wondering that backdrop state is working with marco in your installation, or do you use compiz?

**Comment by flexiondotorg** [comment]
Transmission is fixed using Marco and Compiz. The difference is with Marco the progress bar is always green, regardless of the Transmission window being Active or Inactive. With Compiz the progress bar is grey when the Transmission window is Inactive and green when the Transmission window is Active. There are no white centres in Transmission progress bars after your recent changes using either Marco or Compiz. Therefore, I consider Transmission fixed :-)

**Comment by raveit65** [comment]
> The difference is with Marco the progress bar is always green, regardless of the Transmission window being Active or Inactive.
This mean backdrop state isn't working with marco, known issue
@Are you on irc? you need to test some thingd for apt-manager

**Comment by flexiondotorg** [comment]
Here is the test you requested on IRC. I removed `/usr/share/themes/Ambiant-MATE/gtk-3.0/assets/progressbar-horizontal-fill.png` and performed an install using Ubuntu MATE Welcome. It looked like this:

![install progress no fill](https://cloud.githubusercontent.com/assets/304639/15455640/f79cc074-2051-11e6-94e8-d9dadc19b9ef.png)

The following was spat out on the terminal:

    (ubuntu-mate-welcome:30427): Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Ambiant-MATE/gtk-3.0/assets/progressbar-horizontal-fill.png': Error opening file: No such file or directory

**Comment by raveit65** [comment]
Ok, i will drop using an image for the progressbar.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/24eb9083f6ba42c4f8fe6545dac2f7656b29bf29
Please test, should be fine now.

**Comment by flexiondotorg** [comment]
Excellent. Confirmed fixed :-)
