### ISSUE TITLE
Firefox Menus are not themed appropriately

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#40]
As seen in the attached screen shot the Menu bar entries for Firefox are not themed correctly using Ambiant-MATE and Radiant-MATE. The Menu entries are sqaured off instead of curved at the top. *By comparison Ambiance and Radiance exhibit the correct style*.

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

## Ambiant-MATE (incorrect)

![firefox_menus_ambiant-mate](https://cloud.githubusercontent.com/assets/304639/19174068/101cbcec-8c24-11e6-8f74-bd77b23f8dcf.png)

## Ambiance (correct)

![firefox_menus_ambiance](https://cloud.githubusercontent.com/assets/304639/19174075/191423b2-8c24-11e6-8029-1fa6f0cbc208.png)

**Comment by raveit65** [comment]
You mean the round top corners from selected 'menubar > menuitem' ?

Note, the menu itself use 'menu > menuitem'.

**Comment by flexiondotorg** [comment]
Yes, the rounded top corners.

**Comment by raveit65** [comment]
Please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/00fbb3389ab34d5f2aa9938cff5a0b80f5b4d3ab

**Comment by flexiondotorg** [comment]
Confirmed fixed. Thank you :-)
