### ISSUE TITLE
Time and Date Settings unlock button is incorrectly coloured

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#42]
As seen in the attached screen shot when opening Time and Date (*via System -> Administration -> Time and Date*) the centre of the Unlock button is incorrectly coloured when using Ambiant-MATE and Radiant-MATE. *By comparison Ambiance and Radiance are correct*.

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

## Ambiant-MATE (incorrect)

![ambiant-mate-unlock](https://cloud.githubusercontent.com/assets/304639/19174450/d3f84c60-8c26-11e6-8b85-d2dbf25de5fe.png)

## Ambiance (correct)

![ambiance_unlock](https://cloud.githubusercontent.com/assets/304639/19174454/d9acd806-8c26-11e6-906c-9d683622d684.png)

**Comment by raveit65** [comment]
Try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/bca85276e11ea2eb25bbb04a2125d814f775d76b please.

For me is using GtkNotebook inside a button an application bug.
I suggest to forward this to 'time admin'.

**Comment by flexiondotorg** [comment]
Yes, an upstream bug. I'll see if I can get upstream fixed. Thanks for your work around, confirmed working :-)
