### ISSUE TITLE
Highlighting doesn't persist while hovering over Application categories in Advanced Menu

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#43]
Here is the bug report on Laucnhpad that describes the issue and includes a link to a video demonstrating the issue.
- https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1631330

**Comment by raveit65** [comment]
I noticed that too.
After highlighting is gone gtk3-inspector shows me the 'hover 'state for the category menuitem.
So it should show the styling for 'hover' state.
I see same behaviour with Submarines themes.
Maybe a bug in code?

Off topic:
Submarine themes have the jumping menuitem issue too :)

**Comment by flexiondotorg** [comment]
This was a bug in MATE Menu, which is now fixed.
