### ISSUE TITLE
support better visual keyboard navigation

### ISSUE THREAD

**Issue by raveit65** [flexiondotorg/ubuntu-mate-themes#48]
For this i created the dev-keyboard-land branch as this is a huge work and i guess i need to edit changes.
@flexiondotorg 
You can test this with changes in mate-themes.
With GreenLaguna i set up a very simple styling with using only the **outline** implementation from gtk+, former called focus-line in gtk2.
I think you like a more advanced styling which i did for Menta, Submarines and Traditional themes.
First commit in repo will give us the state what is used in GreenLaguna theme.
For working on that i need your testing and feedback.
For references you can take a look at this report.
https://github.com/mate-desktop/mate-themes/issues/156

**Comment by flexiondotorg** [comment]
I've merged these changes and added the same changes to Radiant-MATE and Ambiant-MATE-Dark.
