### ISSUE TITLE
Restyle GTK2+ and GTK3+ scrollbars based on Tradional themes

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#49]
Please restyle the GTK2+ and GTK3+ scrollbars in Ambiant-MATE, Ambiant-MATE-Dark and Radiant-MATE using TraditionalGreen, from `mate-themes`, as a basis. Please re-touch the colours of the scrollbars to match each theme.

The squared edges of the TraditionalGreen scrollbars are a better fit for the Ubuntu MATE themes and don't suffer from some rendering issues seen with rounded edged scrollbars.

**Comment by raveit65** [comment]
For better communication the GtkScrollbar have several elements.
- Scrollbar itself have 3 elements, 2 up/down buttons and a trough.
- The trough is the element which is around the slider.
In result we have 4 elements, scrollbar, up/down buttons, trough and the slider.
So, i guess you mean the slider with 'rounded edged' ?
And you like to have a colored slider like trad themes?

**Comment by flexiondotorg** [comment]
I'm referring to the scroll buttons and the slider. As for colour perhaps the same colour as the window decoration?

**Comment by raveit65** [comment]
I created a branch for this as i expect more corrections to fix the issue.
A first strike https://github.com/flexiondotorg/ubuntu-mate-themes/commit/35529e5a75925244ac4aca4d25455f1a28bb5b88
with using theme_selected_bg_color (green) for the slider.
And the scrollbar isn't transparent in ff anymore.

**Comment by flexiondotorg** [comment]
I *really* like the simplicity of those scrollbars. Any chance Chromium/Chrome can be styled the same way?

**Comment by raveit65** [comment]
new commits
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/8cfe79ee5437f3ce01750b18242f878d959b92e2
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/4f1702d69267ab43e877b427733246ddfa1875ea

**Comment by flexiondotorg** [comment]
@raveit65 I think you can make the same scrollbar changes to Radiant-MATE.

For Ambiant-MATE-Dark, the same style but I think the slider colour and through colour should be dark. Perhaps use the same colours Ambiant-MATE-Dark uses now and just apply the new shape?

**Comment by raveit65** [comment]
For Radiant:
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/0eefeb1c92f9382c17d822331954b1ca1892af95
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/a8e91bc3af2ee3cc7eb2f6e40cdd15ec7abd6b41
For Ambiant-MATE-Dark:
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6e4f81807280df37a6076a3ef2873730c509aa99
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/8eb3fdb4a759c89480b606ecfed891260a980722
Please test.
If you like to change the color for the slider with AD you can simply change the shade values here.
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/dev-scrollbar/usr/share/themes/Ambiant-MATE-Dark/gtk-3.0/gtk-main.css#L128
and the line below for hover/active color.

**Comment by flexiondotorg** [comment]
Ambiant-MATE and Ambiant-MATE-Dark are great :-)

Looks like there is an issue with Radiant-MATE GTK3+ scrollbar though.

![radiant-mate-scrollbar](https://cloud.githubusercontent.com/assets/304639/24083537/875ffdb4-0cd0-11e7-8b8e-04b1f3d2f780.png)

**Comment by raveit65** [comment]
opps, i forgot to add the new color definitions.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/241676626e18a9e3f9bdcfb0a34c6f2e629a420f

**Comment by flexiondotorg** [comment]
Perfection! Thanks for your hard work on this one. All three look great now :-) Merged to master.
