### ISSUE TITLE
Some buttons in dialogue boxes are squashed together

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#5]
See the attached screen shots for comparison. 

## GTK2

![button_spacing_gtk2](https://cloud.githubusercontent.com/assets/304639/15397465/36796b70-1dd8-11e6-8ac3-0fb22575cd76.png)

## GTK3

![button_spacing_gtk3](https://cloud.githubusercontent.com/assets/304639/15397475/3d8e7450-1dd8-11e6-904d-d5ffdb10ac86.png)

**Comment by raveit65** [comment]
Well linked button are a GTK3 feature and most themes squash them together.
But see how it lloks in Menta themes, here the middle buttons don't have round borders, and it looks nice.
But i can also add a margin, in result it looks like gtk2.

**Comment by flexiondotorg** [comment]
The linked button in the Submarine themes looks nice, but I'd prefer something closer to how it was presented in GTK2. Only slight spacing over what we have now is required.

**Comment by raveit65** [comment]
hmm, it looks like 
https://developer.gnome.org/gtk3/stable/GtkDialog.html#GtkDialog--s-button-spacing
isn't working any more, so adding something like this does not have any effect.
https://github.com/mate-desktop/mate-themes/blob/gtk3.18/desktop-themes/Blue-Submarine/gtk-3.0/gtk-widgets.css#L20
Also using a margin is still ignored
```
.message-dialog .linked.dialog-action-area .button {
    margin: 0px 4px 0px 4px;
}
```
I recall that this was working with older gtk+ versions.
I guess that is the reason why adwaita use a setting with border-radius=0 for middle buttons, to avoid this brokenness ;)
All i can do is to reduce the horizontal padding for this buttons, which reduce the whole horizontal window size, or adding a setting what you see with adwaita, submarine themes and many others.

**Comment by flexiondotorg** [comment]
In which case, your solution in the Submarine themes is the best I've seen (by a long shot) for this issue. Please proceed with that approach as a solution :-)

**Comment by raveit65** [comment]
smaller buttons
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7cfbe6eb9fcb68f3602c029b091c2c976827da2b

**Comment by flexiondotorg** [comment]
I've just tested the latest commit. Perfect :-)

I confirm this issue closed.

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/ae916f38cdb3717d627429f969ac2a2b541576f0
