### ISSUE TITLE
Restyle GTK3+ Notebooks (tabs) based on Tradional themes

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#50]
The GTK3+ Notebook (tab) styling in Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark is poor. 

![notebooks are poorly styled](https://cloud.githubusercontent.com/assets/304639/24004112/5aeb438a-0a5d-11e7-8909-cadff334852c.png)

Please restyle the Notebooks in all three themes using TradionalGreen as a basis, making sure that that `mate-terminal` notebooks are also included. Also ensure that any outline (keyboard navigation enhacements) are also carried over.

*Please only restyle the GTK3+ Notebooks, the GTK2+ Notebooks are fine*

**Comment by flexiondotorg** [comment]
Ignoring notebook style for the moment, some of the base colours in the Ubuntu MATE themes has become too pale. 

## Ambiant-MATE "Padding"

Here is the current Ambiant-MATE theme, **look at the base color where the mouse pointer in located**. The notebook alignment is a bit off in this too and the active/inactive notebooks are not easily distinguishable.

![ambiant-mate-padding](https://cloud.githubusercontent.com/assets/304639/24009375/ae70511c-0a6c-11e7-99e0-facf99d00f0e.png)

## Ambiance "Padding"

Compare that with Ambiance, which uses a darker colour.

![ambiance-padding](https://cloud.githubusercontent.com/assets/304639/24009418/d885d0bc-0a6c-11e7-8dd0-7956df98d1b2.png)

## TraditionalGreen

TraditionalGreen also has this darker base colour, and IMO, looks by far the best. The notebook style here is very clean, the notebooks align neatly with the frame.

![traditionalgreen-padding](https://cloud.githubusercontent.com/assets/304639/24009526/2b2c8db0-0a6d-11e7-9aef-ddd76db61894.png)

## Notebook style

**Comment by flexiondotorg** [comment]
@raveit65 Thanks for the notebook update. Firstly, good job! I think the distinction between the active and inactive notebooks is much improved. There are a couple of improvements I'd like to see though :-)

## Notebook alignment

The active notebooks do not neatly align to the frame/box edges. This can bee seen for all tab orientations on Page 1 of GTK3 Widget Factory. Please can you make the active notebook extend to the edge of what it borders as demonstrated in the theme that can't be named ;-)

![01_tab_alignment](https://cloud.githubusercontent.com/assets/304639/24038522/af21b172-0af9-11e7-8ca3-43c5c6815506.png)

## Active Notebook colour and colour of connecting area

The active notebook colour is `#f9f8f8`, this is too pale. It should be `#f2f1f0`. Also, the area that the notebook connects to (where the mouse pointer is in the image below) should also be `#f2f1f0`.

![02_active_tab_colour](https://cloud.githubusercontent.com/assets/304639/24038627/22d4002a-0afa-11e7-9e62-e739805506a5.png)

## Pulse Audio Volume Control

The area that notebooks connect to should be that same colour as active notebooks. It is currently `#ffffff` but should be `#f2f1f0`. Also the border that encloses all notebooks in `pavucontrol` is missing, a border should be added as seen in the Appearance Preferences screenshot above.

![03_pavu_control_issues](https://cloud.githubusercontent.com/assets/304639/24038725/910979f8-0afa-11e7-8e86-7aef29ddcd10.png)

**Comment by raveit65** [comment]
> The active notebook colour is #f9f8f8, this is too pale. It should be #f2f1f0. Also, the area that the notebook connects to (where the mouse pointer is in the image below) should also be #f2f1f0.

Those are the same elements what you see in gtk3-widget-factory or with a real application where the pointer is located.
Are you sure with #f2f1f0?
This is the color of the general background of windows?
Using the same colors make notebooks undefined?
Btw. i was sure that you ask me that :-)

@pavu-control
Using borders cased a issue with other applications with 3.20 in the past,
To avoid unwanted borders in other apps this is disable here see https://github.com/mate-desktop/mate-themes/issues/130#issuecomment-232128061
But it looks like it is possible with 3.22.
I just testing a fix for this with Blue-Submarine theme local.

**Comment by flexiondotorg** [comment]
> Those are the same elements what you see in gtk3-widget-factory or with a real application where the pointer is located.

The issue is present in actual application and `gtk3-widget-factory`.

> Are you sure with #f2f1f0? This is the color of the general background of windows? Using the same colors make notebooks undefined?

I am pretty sure, yes. All the other themes in `mate-themes` have the same same color where the notebook meets that adjoining area. 

> I just testing a fix for this with Blue-Submarine theme local.

I'll be interested to hear how it goes.
 just testing a fix for this with Blue-Submarine theme local.

**Comment by flexiondotorg** [comment]
Perhaps this helps explain when things should be `#f2f1f0`.

![notebooks annotated 01](https://cloud.githubusercontent.com/assets/304639/24042637/bfb57ef4-0b0a-11e7-815f-9b2009caf701.png)

**Comment by raveit65** [comment]
Here it looks different
![bildschirmfoto zu 2017-03-17_13-13-24](https://cloud.githubusercontent.com/assets/961604/24042742/9930382e-0b13-11e7-8506-734a38235afc.png)

**Comment by flexiondotorg** [comment]
Yep, I pulled again and got 3cf2a4c7fde56fbd268d8ab81c8b36ef3801b44f. That is the background color I was requesting :-)

**Comment by raveit65** [comment]
for pavu-control
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6b65f3e927e01d6aab20656dc12b37707e491bd6

**Comment by flexiondotorg** [comment]
I've tested many applications, I did not see any regressions as a result of https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6b65f3e927e01d6aab20656dc12b37707e491bd6 :-)

**Comment by raveit65** [comment]
Commits for Ambiant are squashed and i added all the stuff to Radiant.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/aa505ff7043d7731e110ab4819b910e562ff2e7b
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/5cf58111b3bad32a8f593432b3eca0ddaed17ba5
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/445de8d8ee5b5216a0432e0521b7cf090832e7b6

**Comment by flexiondotorg** [comment]
So, this is all look much, much better :-) Just one little issue remaining, the active notebooks don't meet the outer edge of their border, like the Traditional themes do. Can you make the outer edge of the active frame meet the border like the inactive notebooks do please.

**Comment by raveit65** [comment]
> Just one little issue remaining, the active notebooks don't meet the outer edge of their border, like the Traditional themes do. Can you make the outer edge of the active frame meet the border like the inactive notebooks do please.

This should make it better hopefully .
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3d39579887f938c497361725745ef3c96b835b33

**Comment by raveit65** [comment]
Notebook border for pavu-control with Ambiant-Mate-Dark.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/dde849c6d89738894106fdfbdd8b3f2fc58f724f

**Comment by flexiondotorg** [comment]
@raveit65 It's so beautiful :-) Thank you for all the hard work, this is a huge improvement. You can merge all this to master :-) When you've merged it, you can close it.

**Comment by raveit65** [comment]
all merged to master.
