### ISSUE TITLE
Headerbar double icon

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#51]
If you open Deja Dup while using Ambiant-MATE, Radiant-MATE or Ambiant-MATE-Dark you will notice you can see the edges of an icon beneath the Backup icon on the far right of the header bar, as shown below:

![deja dup double icon](https://cloud.githubusercontent.com/assets/304639/24004453/46571dc6-0a5e-11e7-976f-d32950fde63d.png)

The TraditionalGreen doesn't exhibit this issue, please restyle that header bar icon in all 3 Ubuntu MATE themes using TraditionalGreen as a basis. If you `apt install menulibre`, you can also see that exhibits the same issue.

See this upstream issue:

  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1630773

**Comment by raveit65** [comment]
I know what's causes the issue, but why not replacing the whole theme with Traditional themes?
Replacing part of it is 2 much work, though.

**Comment by raveit65** [comment]
Why is implementation of using regular icons for headerbars so badly here?
All was done in Menta themes very well ;-)

**Comment by flexiondotorg** [comment]
Replacing the whole theme with Traditional isn't an option, one of the objectives of Ubuntu MATE is to preserve the familiar Ubuntu look and feel. I'm sorry if it is a lot of work to borrow elements from one of your existing themes, we can discuss additional funding if required ☺️

I suspect this aspect of the themes derived from Ubuntu has been overlooked because Unity 7 (a compiz extension) handles all this stuff.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/88618d26bebd52b0600955f44c01b25701287cda

**Comment by raveit65** [comment]
For better understanding.
The issue is caused by using an background-image here which looks like an regular icon.
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L3041
Here and in some places below.
But for the menu button every own csd app pulls in his own specific button.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6cdeebfb4277960f4f834f8d160b60621e1e2797

**Comment by raveit65** [comment]
please test

**Comment by flexiondotorg** [comment]
@raveit65 You correctly interpreted the requirements by preserving the window controls :-) Confirmed fixed, thank you!
