### ISSUE TITLE
Appearance: Interface Tab not rendered correctly.

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#52]
The Preview in the Interface tab accessible from Appearance Preferences it not rendered correctly in Ambiant-MATE, Radiant-MATE or Ambiant-MATE-Dark.

![appearance interface tab](https://cloud.githubusercontent.com/assets/304639/24004591/9ba7a3f4-0a5e-11e7-8016-db8477a99b1e.png)

This preview is rendered correctly in other themes, such as TraditionalGreen and Ambiance (which can be installed via `apt install light-themes`).

**Comment by raveit65** [comment]
Themes make a different between toolbar (light) and primary-toolbar which is dark in Ambiant-Mate.
But the primary-toolbar is missing in appearance-ui file.
Adding the class fixes the issue for me.

**Comment by flexiondotorg** [comment]
@raveit65 I've made the suggested change, the updated `appearance.ui` has been copied to `/usr/share/mate-control-center/ui/apperance.ui`. The toolbar items in the preview are still too tightly packed together in Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark when compared with Ambiance.

## Ambiant-MATE (icons not spaced)

![interface_ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24039496/4c6cfb14-0afd-11e7-8af1-07275e22a1ab.png)

## Ambiance (just right)

![interface_ambiance](https://cloud.githubusercontent.com/assets/304639/24039503/53d70890-0afd-11e7-9af6-be7f65f7d398.png)

**Comment by raveit65** [comment]
hmm
![ambiant-mate-appearance](https://cloud.githubusercontent.com/assets/961604/24039765/a661a83c-0b06-11e7-8b9b-48b8e2dc5fe1.png)
