### ISSUE TITLE
Headerbar button border ugliness

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#54]
If you `apt install menulibre` and run it you'll notice the buttons in the header bar look quite ugly in Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark.

![menulibre header bar buttons](https://cloud.githubusercontent.com/assets/304639/24005211/511116b6-0a60-11e7-853f-b922f3fb1023.png)

Other themes, such as Ambiance and TraditionalGreen, do not exhibit this issue.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/d0c525de996e6dda60b89821531bed4c88a5a762
I don't know what exactly causes the issue.
But using those setting for the insensitive buttons there fixes the problem.
    border-image: none;
    border-color: transparent;
    background-color: transparent;
Maybe something wrong with including the background-image for the border?

**Comment by flexiondotorg** [comment]
I'll test this is a little bit. Yes, I suspect the background image is at the heart of this issue.

**Comment by flexiondotorg** [comment]
@raveit65 This is sorted for Ambiant-MATE and Radiant-MATE. No change for Ambiant-MATE-Dark required?

**Comment by raveit65** [comment]
No, button:disabled looks OK here with dark theme

**Comment by flexiondotorg** [comment]
Confirmed fixed. Many thanks, closing :-)
