### ISSUE TITLE
Headerbar search box blurred font

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#55]
If you `apt install menulibre` and run it you'll notice the font in the search box is blurred when using the Ambiant-MATE theme. This issue is not present in Radiant-MATE. This issue also affects Blue Submarine and Green Submarine from `mate-themes`, althought the other `mate-themes` are not affected.

![menulibre blurred search font](https://cloud.githubusercontent.com/assets/304639/24005388/c9060244-0a60-11e7-89f6-8cda47f033c8.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3ebfb5bb2046a43ba8f6c896bb1b6a20f3e88ffc

**Comment by flexiondotorg** [comment]
Tested all 3 themes, confirmed fixed. Thank you :-)
