### ISSUE TITLE
Radiant-MATE window border colour without compositing is too dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#56]
While using Radiant-MATE, if you use MATE Tweak to change to Window Manager to "Marco (No compositor) and then open an application that requires CSD, such as Deja Dup, Menu Libre or Plank Preferences the windows border color is black. This is incorrect, the window border should be a mid brown colour as used by any non-CSD application.

![radiant-mate-no-compositing](https://cloud.githubusercontent.com/assets/304639/24040230/417f4182-0b00-11e7-90b2-1bdd54c88386.png)

**Comment by raveit65** [comment]
whoow, mate-tweak is a a c-s-d window -_-

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/59242960820049aa72d29db71cc5f55b093b0a48
Please test.

**Comment by flexiondotorg** [comment]
No change as far as I can tell, border is still black.

**Comment by flexiondotorg** [comment]
Hmm, after merging with master this is now correct :-) Thanks!
