### ISSUE TITLE
Hovering some links are not rendered correctly

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#57]
When hovering over some links, in Appearance Preferences for example, they are rendered only with a change of font colour when they should have a button drawn around them. This effects Ambiant-MATE, Radiant-MATE and Ambinat-MATE-Dark.

## Ambiant-MATE (wrong)

![link-hover-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24043422/62646a40-0b0e-11e7-8f94-0ca459e52280.png)

## Ambiance (correct)

![link-hover-ambiance](https://cloud.githubusercontent.com/assets/304639/24043448/8152c49c-0b0e-11e7-8ff7-8d5bebf993aa.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9189c957b4e097c95c09f9b2765a69307f56be60
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/445de8d8ee5b5216a0432e0521b7cf090832e7b6
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/322a2f58ff4364f501f86afe598b130145c764fd
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/ce2aad30ea0def127a0bb3521ab76218c8a85945
All in dev-notebook branch as it is a problem with notebook settings.

**Comment by flexiondotorg** [comment]
Confirmed fixed. Thank you :-)
