### ISSUE TITLE
Ambiant-MATE-Dark button and notebook borders are light and should be dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#58]
The Ambiant-MATE-Dark uses light coloured borders for Buttons and Notebooks, this looks ugly and incorrect. The borders should be a suitable dark colour.

**Comment by raveit65** [comment]
first fix, you won't like it ;-)
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/dc42e5621ce68fad494a200c35914855a1511bd7

**Comment by raveit65** [comment]
notebooks
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6ffd57eb18e44711273fb5fbacefd68814e07f13

**Comment by raveit65** [comment]
progressbars
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/b6e6d8873af25420e3e4cd9b756ff599e5b54123

**Comment by flexiondotorg** [comment]
@raveit65 This is all looking really great :-) Can you also look into:

  * Switches in the off position appear vertically offset too high
  * Make the scales/sliders use the dark background
  * Make the separators in Firefox menus dark, like in Ambiant-MATE

**Comment by raveit65** [comment]
GtkScale
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/58618590971edb45b32d606162d3242108e8da36
The slider itself use a tons of images which are all light, see https://github.com/flexiondotorg/ubuntu-mate-themes/blob/dev-borders/usr/share/themes/Ambiant-MATE-Dark/gtk-3.0/gtk-widgets-assets.css#L562
I think i need to steal some images from another dark theme, maybe here
https://github.com/raveit65/mate-themes-extras/tree/master/desktop-themes/DeLorean-Dark/gtk-3.0/assets

**Comment by flexiondotorg** [comment]
I'm going to merge this to master, the most important changes have been made (Notebooks and Though) and look great. We can progress the remaining issues in master :-)

**Comment by flexiondotorg** [comment]
@raveit65 Don't worry about replace image assets for now. There are the more important changes that are required IMO:

  * In Ambiant-MATE-Dark make the separators in Firefox menus dark, like in Ambiant-MATE
  * Switches in the off position appear vertically offset too high

**Comment by raveit65** [comment]
Hmm, the separators in ff menu (bookmarks) are dark here same like with Ambiant-Mate.
Well this is with ff-52.0 in f26, need  to check that in 17.14.
Indeed this is broken with ff-51 in ubuntu.
Are there chances that ubuntu will update to 52 with 17.04 release?

**Comment by flexiondotorg** [comment]
@raveit65 Yes, it should update to 52. So lets wait and see what happens for a bit on that one.

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/4df2a9d0d22879a75b34ee4434056b3ecb93ce1d
Looks like we don't need this hack for ff-52 :-)
```
/* fix for broken firefox */
menu separator,
menu .separator {
    color: shade(@dark_bg_color, 0.9);
 }
```

**Comment by flexiondotorg** [comment]
So Firefox 52 is in proposed. I just testing FF 52 now.

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/a410273fa44aa46943b07cf9a19704088ab121d2
This fixes GtkSwitch

**Comment by flexiondotorg** [comment]
@raveit65 The switches in Ambiant-MATE-Dark look great :-)

However, the switches in AMbiant-MATE no longer toggle, just the through colour is changed.

**Comment by flexiondotorg** [comment]
The issues discussed here are resolved or have their own issue open.
