### ISSUE TITLE
Expander hover over in Ubiquity should not change text colour

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#59]
When installing Ubuntu MATE via Ubiquity with the Ambiant-MATE theme selected and hovering over the expander to show more details changes, the fonts change to dark text. This should not happen and the text colour should not change, as shown in the Ambiance theme.

This issue was introduced during the big update to GTK3, possibly is one of these commits:

  * https://github.com/flexiondotorg/ubuntu-mate-themes/commits/c1d7522dbdff8be734d5779c6919e0a481676be0/usr/share/themes/Ambiant-MATE/gtk-3.0/apps/other-applications.css

## Ambiant-MATE (wrong)

![ubiquity_ambiant_mate](https://cloud.githubusercontent.com/assets/304639/24054026/ba166e54-0b32-11e7-9b7d-4eace2ab8458.png)

## Ambiance (correct)

![ubiquity_ambiance](https://cloud.githubusercontent.com/assets/304639/24054028/bd5eafe0-0b32-11e7-9cd8-e22736533438.png)

**Comment by raveit65** [comment]
What is the command line of Ubiquity again?
And is this testable w/o installing Mate again?

**Comment by raveit65** [comment]
We can try
```
expander,
expander label,
expander > title > label {
    color: @fg_color;
}
```
at https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L838

**Comment by raveit65** [comment]
hmm, using this in a live session does not have any effect.
I need to have a link to ambiance at launch pat to take a look at gtk-widget.css.

**Comment by flexiondotorg** [comment]
@raveit65 http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/files

**Comment by raveit65** [comment]
Ok, i found out that https://github.com/flexiondotorg/ubuntu-mate-themes/commit/ce2aad30ea0def127a0bb3521ab76218c8a85945#diff-7ef511d801f631dd7a533b5e7456d61dL1396
already fixes the issue.
What  a mess with using wildcards.
One more reason to merge this branch.

**Comment by flexiondotorg** [comment]
Excellent detective work :-) I'll test over the weekend.

**Comment by raveit65** [comment]
I rebased dev-notebook branch against master, means all changes are in thisbranch, and coppied all themes from this branch into the live system to be sure.
The issue is fixed with mentioned commit. :-)

**Comment by flexiondotorg** [comment]
Thanks for rebasing, this all looks great. I'll make a test package in a PPA so I can test the Ubiquity fix.

**Comment by flexiondotorg** [comment]
Ubiquity is fixed :-) Thank you!
