### ISSUE TITLE
GTK2 and GTK3 scrollbars are different

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#6]
The GTK2 and GTK3 scrollbar designs are different, they should be the same or very similar. The current GTK3 scrollbar was hacked together by @flexiondotorg and are horrible and @flexiondotorg isn't all that keen on the GTK2 scrollbars either. Something simpler for both is fine :-)

## GTK2

![scrollbars_gtk2](https://cloud.githubusercontent.com/assets/304639/15398309/0b3e2092-1ddb-11e6-9294-ace0b1dcabd0.png)

## GTK3

![scrollbars_gtk3](https://cloud.githubusercontent.com/assets/304639/15398317/104b2c7e-1ddb-11e6-8fb3-7884fd18b88e.png)

**Comment by flexiondotorg** [comment]
@raveit65 The scrollbar design you've used in BlueMenta in mate-themes 3.18.1 would be suitable :-)

**Comment by flexiondotorg** [comment]
@raveit65 I've just tested Menta, those scrollbars are ideal :-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/5011cae6a6b87b295b4cd6d143e92735e440a611
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e74fc20fda5b664e1e9252f7bd2db0e11def571d
taken from Menta themes.

**Comment by flexiondotorg** [comment]
@raveit65 Can the GTK2 Menta scrollbars also be added?

**Comment by raveit65** [comment]
@flexiondotorg 
sure, both themes use the murrine engine, should be no problem.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7c396ed0425f5fdc4cabe31d08cce7446f4bfb2d
Does that work?

**Comment by flexiondotorg** [comment]
Perfect! :-)

I confirm this issue closed.

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done https://github.com/flexiondotorg/ubuntu-mate-themes/commit/4b849fc9d46d3b2e00ad4cabe21a0cc55063168a
