### ISSUE TITLE
pavu-control incorrect base colour

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#60]
In Ambiant-MATE and Radiant-MATE (and Ambiant-MATE-Dark) a section of `pavu-control` is the wrong colour. See the example below:

## Ambiant-MATE (wrong)

The area the mouse pointer is should be `#F2F1F0` not `#FFFFFF`

![pavu-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24061571/d5846106-0b4f-11e7-8ad5-3acf702c8c6c.png)

## Ambiance (correct)

![pavu-ambiance](https://cloud.githubusercontent.com/assets/304639/24061578/de6af208-0b4f-11e7-9d0e-61913e2479eb.png)

**Comment by raveit65** [comment]
I need kill all remnants from previous maintainers and settings which were blind ported from < 3.20 ;-)
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/eaabc8eef944bf0984034d12d491d330fa7ba015

**Comment by flexiondotorg** [comment]
Perfect! That looks great, thank you :-)
