### ISSUE TITLE
Headerbar toggles a too high and distort window control icons

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#61]
Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark all exhibit an issue where toggles in the header bar are too high and consequently cause the window control icons to get stretched vertically. This can be best seen in Deja Dup (System -> Preferences -> Other -> Backup).

## Ambiant-MATE (wrong)

![dejadup-toogle-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24080304/0b5c27c4-0c94-11e7-8aa9-02791f985d2e.png)

## Ambiance (correct)

![dejadup-toggle-ambiance](https://cloud.githubusercontent.com/assets/304639/24080310/0f837230-0c94-11e7-95a2-8673a26e38d7.png)

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/d1f7123abc33800c2cb21ed8001dc9ebdb0d8235
I remove also the text-shadow for switch:disabled
With gtk3-widget-factory using text-shadow seems to be fine for switch and switched:checked
Not sure how i can enable the switch in deja-dup here.

> This can be best seen in Deja Dup (System -> Preferences -> Other -> Backup).

It is OK for me if you post a command line ;-)

**Comment by raveit65** [comment]
Not if that commit fixes the missing window control icons in your screenshot, but i see them here in 17.04 with normal layout.
![deja-dup](https://cloud.githubusercontent.com/assets/961604/24081474/ac3c15b2-0cb4-11e7-8828-3043492a66f6.png)

**Comment by flexiondotorg** [comment]
Thanks! Confirmed that the switch height is fixed in all three themes :-)
