### ISSUE TITLE
File-Roller toolbars have ugly borders

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#62]
If you `apt install file-roller` on Ubuntu MATE 17.04 and run it you'll notice the "toolbar" has ugly border around the icons. This issue is present in Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark.

![file-roller-toolbar-borders](https://cloud.githubusercontent.com/assets/304639/24083695/f973e228-0cd3-11e7-8516-9c46a8955b0c.png)

**Comment by raveit65** [comment]
try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/f178c1c9c4eb0ad82006dc8580c59b89d544e4fa
please

**Comment by flexiondotorg** [comment]
Confirmed fixed in all 3 themes. Thanks!
