### ISSUE TITLE
Brisk Menu should have a dark theme in Ambiant-MATE

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#63]
Brisk Menu is installed by default in Ubuntu MATE 17.04, it can be added to the panel in the usual way. Brisk Menu is rendered with a light theme when using Ambiant-MATE but it should be rendered with a dark theme, just like this other menus.

See Brisk Menu when using Ambiant-MATE-Dark for an example of how it should be rendered when using Ambiant-MATE. Perhaps this will be useful reference from upstream:

  * https://github.com/solus-project/brisk-menu/blob/master/data/styling.css

**Comment by raveit65** [comment]
A first implementation.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/afe9667ad913730fba7fb2dae81424d86996ed22

**Comment by raveit65** [comment]
branch is rebased
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/617775fd54eb9f123e444fd8c68c91f0569064e3

**Comment by raveit65** [comment]
For some reasons the border-image for buttons does not work.
But without using gtk3-inspector this isn't possible to fix.
This should be fixed by upstream.

**Comment by flexiondotorg** [comment]
I've made some tweaks and applied the same style to Radiant-MATE and Ambiant-MATE-Dark. Merged to master :-)
