### ISSUE TITLE
Check boxes in Ubiquity's partition tool have incorrect background colours

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#64]
Ambiant-MATE, Radiant-MATE and (to a lesser extent) Ambiant-MATE-Dark have an incorrect background on the check boxes in the Ubiquity partition creation tool.

Fortunately this component of Ubiquity (the Ubuntu installer) can be tested on an installed system.

    sudo apt install ubiquity ubiquity-gtk-frontend

You can start Ubiquity as follows:

    ubiquity gtk_ui

The click *Continue*, *Continue*, select *Something else* and click *Continue*. When asked if you want to unmount `/dev/sda/` answer *No* and you'll see the partition creation tool, as shown below. Don't actually partition anything or attempt to install `;-)`

## Ambiant-MATE (wrong)

![ubiquity_partition_ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24092630/5168e352-0d47-11e7-8f0d-d7889974d74e.png)

## Ambiance (correct)

![ubiquity_partition_ambiance](https://cloud.githubusercontent.com/assets/304639/24092636/592c8ada-0d47-11e7-9d60-846154bfc4fb.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/6e4b5944cf995798a347ce5fca00444c12aa6fca
Fix is for all themes.

**Comment by flexiondotorg** [comment]
Confirmed fixed in all 3 themes. Thank you!
