### ISSUE TITLE
Terminix Preferences white headerbar dividing line and incorrect headerbar corners

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#65]
In Ambiant-MATE the preferences in Terminix (`apt install terminix`) has a white dividing line in the headerbar, this should be dark as seen in the Ambiant-MATE-Dark theme.

Additionally, the headerbar corners in all 3 themes is incorrect with a square edge visible over the rounded corner.

![terminix-preferences](https://cloud.githubusercontent.com/assets/304639/24096314/1a3be908-0d59-11e7-9999-bde3b44b20a5.png)

**Comment by raveit65** [comment]
Terminix developer should use the same widgets for their main and preferences window.
For the main window they use headerbar.titlebar, and for preferences window they use only headerbar.
In our themes only headerbar.titlebar use round top edges.
The other one is use for ie. file-roller , here the headerbar is used as second bar below the menubar, see https://github.com/flexiondotorg/ubuntu-mate-themes/issues/62
Using round edges for headerbar too makes file-roller looking ugly, See blue-submarine themes. Here i need to fix that.
So this needs to be fixes by terminix.
The other issue i can fix.

**Comment by raveit65** [comment]
fix for the light separtor
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9e5b31048f0800ed0d98f23ac1f2cf11a7119cf6
Please test.

**Comment by flexiondotorg** [comment]
I understand what you've said about the headerbar corners, no problem. I'll contact Terminix.

As for the separator, confirmed fixed. Thank you :-)
