### ISSUE TITLE
Lock screen rounded corners are not transparent

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#66]
Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark all exhibit an issue when the screen is locked, the lock screen credential entry dialogue window has rounded corners but the corners are not transparent so each corner has little "ears". This issue appears to affect all themes in `mate-themes` 3.22.7 too.

Can the corners of the lock screen credentials dialogue window be made properly rounded, like the LightDM login screen.

## Ambiant-MATE

![lockscreen-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24096857/420a4734-0d5b-11e7-83e6-96a07543637a.png)

## Ambiant-MATE-Dark

![lockscreen-ambiant-mate-dark](https://cloud.githubusercontent.com/assets/304639/24096864/4a57ba5c-0d5b-11e7-9cc7-021d67333340.png)

**Comment by raveit65** [comment]
This is the well known black frame problem.
I don't know why we have this problem with mate-screensaver code.
We use rounded edges already
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/apps/mate-applications.css#L503
Try increase the radius for .lock-dialog {} and .lock-dialog frame { } and you will see what madness will happen.
You will always see a black frame behind the dialog window.
For this reason i used a small radius here.
Another solution is to use radius=0px .

**Comment by flexiondotorg** [comment]
@raveit65 In which case for the Ubuntu MATE themes can you please make this dialog have a square edge with the existing border colour currently used by each theme.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/56c599a50cef56178a5287ed4720f69fa5fae291

**Comment by flexiondotorg** [comment]
Thanks, much better :-) Confirmed fixed for all 3 themes.
