### ISSUE TITLE
Button highlights in shutdown dialogue are too thick

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#67]
Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark all exhibit the same issue in the shutdown dialogue, the button highlighting is too thick. Can the shutdown button highlights be made thinner as seen in the Ambiance theme.

## Ambiant-MATE (too thick)

![shutdown-ambiant-mate](https://cloud.githubusercontent.com/assets/304639/24097533/23a36304-0d5e-11e7-87a6-ccf81e6665e0.png)

## Ambiance (just right)

![shutdown-ambiance](https://cloud.githubusercontent.com/assets/304639/24097539/26cff9e8-0d5e-11e7-8ffe-8841bfbd6bf7.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e20b08ea128dad9a7a2807b74e190d8b70fb97d8
for all themes.

**Comment by flexiondotorg** [comment]
Much improved, thank you :-) Confirmed fixed for all 3 themes.
