### ISSUE TITLE
No listview background for unfocused selected items

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#68]
All 3 themes are affected by this issue, unfocused selection in listviews has no background colour, and is thus invisible.

## Steps to reproduce:

Open Caja, select a few files, press F3 to open the extra pane, click into the new pane. When the initial pane loses focus, the selected items become transparent.

However, selecting another theme (such as TraditionalGreen) the issue is not present.

## Upstream report

  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1633880

**Comment by raveit65** [comment]
I can reproduce this.

**Comment by flexiondotorg** [comment]
I can't reproduce using Ubuntu MATE 17.10 daily.
