### ISSUE TITLE
Sound applet in Ambiant-MATE has a light border

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#69]
The border for the sound applet (Indicators disabled in MATE Tweak) has a light coloured border, it should be dark.

**Comment by raveit65** [comment]
please test
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/4e2a156e6afdb6e40b2dc861fb1904b084dc2953

**Comment by flexiondotorg** [comment]
Confirmed fixed, thank you :-)
