### ISSUE TITLE
GTK2 and GTK3 tooltips differ slightly

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#7]
GTK2 tool tips have squared edges and GTK3 tool tips have rounded edges. Tool tips should look the same on, or very similar, on GTK2 and GTK3. The design of the existing GTK3 tooltips is preferred but don't need to have gradients.

**Comment by lah7** [comment]
### GTK 2
![image](https://cloud.githubusercontent.com/assets/13032135/15403239/ef6580c6-1def-11e6-98b2-201b58864725.png)


### GTK 3
![image](https://cloud.githubusercontent.com/assets/13032135/15403206/ceb39d4a-1def-11e6-872f-0999ee0ff905.png)

**Comment by raveit65** [comment]
Well, the gradients i can remove, but i'm not sure if round corners are working with gtk2.

**Comment by flexiondotorg** [comment]
@raveit, please drop the gradient. 

@lah7 I don't have rounded corners in my MATE 1.12 running GTK2. Confused.

**Comment by flexiondotorg** [comment]
Compiz 0.9 in Ubuntu doesn't expose CSD compositing to GTK3, therefore the rounded corners on the tool tips don't render correctly. I request that the tool tips are either square corners or support `solid-csd` to square corners when a Compositor isn't available.

**Comment by lah7** [comment]
@flexiondotorg Interesting, this is the behaviour under 16.10's `crazy-mate` (1.14):
* None = Square
* Marco = Rounded
* Compton = Rounded
* Compiz = Square

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/721cb302f9e9fc0649f6c3c732e1b8cb87e98d2a
- border radius is 0 for both toolkit versions
- gradients is removed from gtk3

I'm not sure about border styling in gtk2, it's a bit hard to test in a gtk3 environment, and using a alpha value for the border color is impossible for gtk2.

**Comment by flexiondotorg** [comment]
Excellent. Looks much better. I have GTK2 applications I could test.

Confirming this as closed :-)

**Comment by flexiondotorg** [comment]
@raveit65 Please migrate the fix to Radiant-MATE

**Comment by raveit65** [comment]
done
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/d231787b4f16b0320391d5517483a4c2c88529d2
