### ISSUE TITLE
The font colour on inactive Notebooks should be dimmed slightly

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#70]
This is a minor issue affecting all 3 themes. The font on inactive Notebooks should be dimmed slightly so the active Notebooks are better highlighted.

**Comment by raveit65** [comment]
I can only lower the contrast between font and background color of the inactive tab.
Can you test this example for Ambiant-Mate please?
```
notebook header tab:checked label {
    color: @theme_fg_color;
    font-weight: normal;
}

notebook header tab label {
    color: shade (@theme_fg_color, 1.40);
    font-weight: normal;
}
```
Add this to the end gtk-widgets.css and play a bit with the shade value.

**Comment by flexiondotorg** [comment]
That is just what I was was requesting :-) Can you make this change for all three themes please.
