### ISSUE TITLE
Outside edge of Notebooks is slightly too dark

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#71]
This minor issues affects of 3 themes. The outside edge of active Notebooks is slight darker than the border it meets. Can is be made to match the colour of the border it meets. Here are some screenshot to help identify what I'm referring too, most easily seen in Ambiant-MATE-Dark.

## Ambiant-MATE

![page1_ambiant-mate-borders](https://cloud.githubusercontent.com/assets/304639/24157269/d7cb5f74-0e50-11e7-9f3d-835c9ef36e6b.png)

## Ambiant-MATE-Dark

![page1-ambiant-mate-dark-borders](https://cloud.githubusercontent.com/assets/304639/24157270/d7cc5208-0e50-11e7-818f-27a68752d10e.png)

## Radiant-MATE

![page1_radiant-mate-borders](https://cloud.githubusercontent.com/assets/304639/24157271/d7d1b162-0e50-11e7-8341-41a6fbfd212c.png)

**Comment by raveit65** [comment]
What you see here is a double border.
One from the tab and one from the notebook itself.
If i remove the border from the active tab, than the tab looks weird it the active one is in the middle or at the end.

**Comment by raveit65** [comment]
fixed in A&R
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/ce17268a934bfe5d6b841d49c361dad8562f3172

**Comment by raveit65** [comment]
fix for AD
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7877e17a666c1829f39e9b7a2a5f023a2da2bdde
Please test.

**Comment by flexiondotorg** [comment]
That is great. Thank you, confirmed fixed :-)
