### ISSUE TITLE
Levelbars in gtk3-widgets is not styled correctly

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#72]
This is a minor issue that affects all 3 themes. Included a screen shots to identify the incorrectly styled Levelbars. Please style Levelbars more similarly to how they're show in Ambiance.

## Ambiant-MATE

![page1_ambiant-mate-thing](https://cloud.githubusercontent.com/assets/304639/24157456/4871dfaa-0e51-11e7-9939-c5f9e3a6b315.png)

## Ambiance

![page1-ambiance-thing](https://cloud.githubusercontent.com/assets/304639/24157469/5304cf18-0e51-11e7-8c3b-cf8c8fa55172.png)

**Comment by raveit65** [comment]
Well it's not the 'thing' from another world, let's say it is the trough from the levelbar :-)
Indeed the background is wrong here, nice finder.

**Comment by raveit65** [comment]
Please test
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/89cfcea6c79ef9139aa4c9541a9a3a1ecca5d731
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/81f7b30eff99de0bedc3f0b0d5c07e26974ea11d

**Comment by flexiondotorg** [comment]
OK, so the levelbar now has the correct through :-)

Can you change the green of the levelbar to match the Ubuntu MATE green used elsewhere please? Could you also make the levelbar slightly fatter, as seen in the Ambiance screenshot.
