### ISSUE TITLE
MATE Menu styling has regressed

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#73]
MATE Menu, in all three themes, is no longer styled correctly. MATE Menu can be enable via MATE Tweak and checking "Enable Advanced Menu" or adding MATE Menu to an existing panel.

**Comment by flexiondotorg** [comment]
From IRC:

```
<@raveit65> ok, by the way mate-menu sucks
<@raveit65> it does really make things that i don't expected
<@raveit65> not sure if it is fixable
<raveit65> flexiondotorg, it seems it comes from https://github.com/flexiondotorg/ubuntu-mate-themes/commit/5beb743001a1d4d6f2866ac4539dad16b26dcca1
<@raveit65> since i remove :not(widget) here it writes a light bg on widget
<@raveit65> but using 'widget' with not is wrong
<@raveit65> as 'widget' is a placeholder for GtkWidgets which don't use his own css nodes name with gtk+-3.20
```

**Comment by raveit65** [comment]
Better fix for mate-screenshot to avoid a collateral damage
with mate-menu ;-)
Please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/5f325bb35a23bb9ccdcb5e32a699e52a8706daae

**Comment by flexiondotorg** [comment]
Indeed MATE Menu is corrected, but this change has caused the Brisk Menu styling to regress :-(

**Comment by raveit65** [comment]
fix for mate-menu
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3405b57aa799ce08c5e7ca53a33f1c6e716b732e
Please test

**Comment by flexiondotorg** [comment]
Confirmed the Brisk Menu and MATE Menu are both looking good again :-) 

Could you make one last tweak to MATE Menu for Ambiant-MATE and Ambiant-MATE Dark. Please change the scrollbar slider to be a solid colour, green for Ambiant-MATE and dark grep for the Ambiant-MATE Dark. No need to change the troughs.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/a9f8d40aba7131a61894b17562e830d85154d601
If this isn't sufficient i can look at it again next month.

**Comment by flexiondotorg** [comment]
This is great! Thank you. Confirmed fixed.
