### ISSUE TITLE
MATE Terminal has white window borders when maximised

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#74]
When MATE Terminal is maximised while using the Ambiant-MATE and Radiant-MATE themes a white border is visible down the left sides (probably the right too) and along the bottom. This is most noticeable when using the default Ubuntu MATE panel layout.

**Comment by raveit65** [comment]
This comes from metacity theme not from gtk+ theme, in result i can't make a different border only for mate-panel.
You only see that because the background of the virtual-terminal-engine is dark compare to other applications.
If i use a dark color in metacity theme you will see the issue with all other applications.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/4f4df89865074a31eed78ddd9bd548f1444dfb10
Note: this doesn't fix the white border from metacity theme, but eliminates a border which comes from pavu-control notebook settings.

**Comment by raveit65** [comment]
...or maybe this was a lucky punch and fixes the issue :-)
I don't see the white border anymore, please test.

**Comment by raveit65** [comment]
Hmm, forgot what i said, the border is there but i didn't saw that because my VM runs in maximize window mode and the edge was cutted on the screen.
But i think it's a bit better.

**Comment by flexiondotorg** [comment]
Fixed with Marco, at least as far as I can tell.

@raveit65 However it looks like a similar issue to #82 now. When using Compiz or Metacity bringing any window to the foreground (and not having a maximised window anywhere) a white line is now visible down the right side of the screen.

**Comment by raveit65** [comment]
I commited on dev-metacity branch a proposal for using a dark thin border in general for windows.
For me this defines a normal light window more and solves the problem with a dark terminal window.
Please test.

I will check if there is a backdrop state on terminal notebook with metacity.

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/2c581413ee0a3d1fa1ce157fd364fd74fb01bb17
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/9826f00c5a5fbcf7388f4dd8417ffd9a5b32df78
