### ISSUE TITLE
Switches are not clearly defined

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#75]
In Ambiant-MATE and Radiant-MATE the switches looks a little unclear. However, the GtkSwitch rework in Ambiant-MATE-Dark (https://github.com/flexiondotorg/ubuntu-mate-themes/commit/a410273fa44aa46943b07cf9a19704088ab121d2) looks fantastic. 

Can the same improvements be made to Ambiant-MATE and Radiant-MATE?

**Comment by raveit65** [comment]
please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/0d4ab523a74ea1c84d25b86128e3018049dac5da
it's for Ambiant-Mate

**Comment by raveit65** [comment]
and Radiant https://github.com/flexiondotorg/ubuntu-mate-themes/commit/80765fae9998a3dbf376e95fa890633a0798daad
Please test.

**Comment by flexiondotorg** [comment]
@raveit65 Ambiant-MATE looks great but Radiant-MATE slider doesn't switch position on Page 1 of `gtk3-widget-factory`.

**Comment by flexiondotorg** [comment]
@raveit65 I've also noticed the Ambiant-MATE switches in headerbars are dark. Nice! However, the switch is slightly too dark. Please make the headerbar switch in Ambiant-MATE that same colour as in Ambiant-MATE-Dark.

**Comment by flexiondotorg** [comment]
@raveit65 I've made the switch slider in Ambiant-MATE header bars the correct color via https://github.com/flexiondotorg/ubuntu-mate-themes/commit/2494d44f1637eb471d3edc78b5fe8ea8ffc81fef

The Radiant-MATE and Ambiant-MATE switches still look different to those in Ambiant-MATE-Dark, is it possible to style the the same?

**Comment by raveit65** [comment]
no

**Comment by flexiondotorg** [comment]
OK, merged :-) https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7a87db9b09179418a60b64f32d66765e5bec11e2
