### ISSUE TITLE
Popover contents are too condensed

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#76]
This issue in present in all 3 themes, the contents of pop overs is too crammed together. Can they be padded out a little more similar to how popovers are displayed in the Ambiance theme.

**Comment by raveit65** [comment]
please test.
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/3a59a1ee8344787d2d860fba963f99918114a6de
If that works in all places we can use that for other themes.

**Comment by flexiondotorg** [comment]
@raveit65 Yep, that look great.

**Comment by raveit65** [comment]
the other themes
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/b4cfa1d6bc8483d73b405a0d2780b8e9fa0f01db

**Comment by flexiondotorg** [comment]
Confirmed fixed. Thanks!
