### ISSUE TITLE
Keyboard Preferences -> Add Layout: No borders around keys

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#78]
If you add a keyboard layout via Keyboard Preferences none of the sample keyboard layouts have borders around the keys, as was the case in the GTK2+ version, this means many of the keys can't be seen properly.

I can't find any GTK3+ theme that draws borders around the keys so perhaps the solution is to make the background used in the preview something not white. This affects Ambiant-MATE and Radiant-MATE.

**Comment by raveit65** [comment]
First we need to add a specific style class to code as the dialog has only general selectors.
If this is done i can darken the whole white bg.
A single key can't be selected here.

**Comment by raveit65** [comment]
Btw. you can speed up the process with a review ;-)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/556dc137e8fda1a6ba26d14e2b1125185c6942ea
Should work when commits from m-c-c are applied.

**Comment by flexiondotorg** [comment]
Thank you!

**Comment by raveit65** [comment]
better fix :-)
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/ed82b81fae62459c6d4bad8a2fdfaee370b061b5
In this way it looks exactly like before in gtk+2.

**Comment by raveit65** [comment]
And it fixes the key map in layout-chooser dialog.
