### ISSUE TITLE
GNOME Character Map with Ambiant-MATE Dark has light background for character grid

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#79]
When viewing GNOME Character Map with Ambiant-MATE Dark the background of the character grid it light when it should be dark.

![gnome-character-map](https://cloud.githubusercontent.com/assets/304639/24354650/99f64e18-12ea-11e7-8fea-849012029cac.png)

**Comment by raveit65** [comment]
Please test https://github.com/flexiondotorg/ubuntu-mate-themes/commit/95df650d116553e5f8065a215a175fd122ddaafb

**Comment by flexiondotorg** [comment]
Confirmed fixed. Thanks!
