### ISSUE TITLE
Notifications using the Slider theme are dark in GTK2 and light in GTK3 

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#8]
Notifications displayed using the Slider theme (the default in Ubuntu MATE) are dark in GTK2 and light in GTK3. The Slider theme in GTK3 should be dark, like the GTK2 version.

## GTK2

![slider_notification_gtk2](https://cloud.githubusercontent.com/assets/304639/15399606/44ba7e7e-1de0-11e6-8415-42ae401cac09.png)

## GTK3

![slider_notification_gtk3](https://cloud.githubusercontent.com/assets/304639/15399614/4ad8308a-1de0-11e6-92c3-1f31c6a75f85.png)

**Comment by raveit65** [comment]
This comes from m-n-d theme itself, not a ubuntu theme issue
slider theme is simply different from gtk2 version, btw. i think with gtk3 is something working which was always broken in gtk2.
You can close this issue.

**Comment by flexiondotorg** [comment]
OK, fair enough. I'll live with it :-)
