### ISSUE TITLE
Pressed buttons in Ambiant-MATE Dark have thick light borders

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#80]
When pressing some buttons in Ambiant-MATE Dark the have thick light coloured borders. This can be most easily reproduced using MATE Calc, see the screen shot below. Please can these border be made thinner and possibly a more fitting colour or perhaps just darken the button to signify it is pressed.

![mate calculator](https://cloud.githubusercontent.com/assets/304639/24355072/66929db8-12ec-11e7-9de8-3ff67d063a97.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/7d6112cf0146e7a7e39d5a2d12dcbce0fbcd5d3b

**Comment by flexiondotorg** [comment]
Confirmed fixed. Thank you :-)
