### ISSUE TITLE
Some Ambiant-MATE-Dark buttons and comboboxes glow too much when hovered over

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#81]
When using Ambiant-MATE Dark some button and combo boxes have a thin green border when selected, this is fine.

But when hovered the border has too much "glow" and looks ugly. Could these buttons and comboboxes change the button color to a dark variant when hovered (like the other buttons/comboboxes) and continue to use the thin green border when hovered.

![too-much-glow](https://cloud.githubusercontent.com/assets/304639/24356933/b236bf86-12f3-11e7-89c3-5c5ba7bdb9d8.png)

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/eb48bf2a3285bfcabb22704cfa435296da52dda0
Please test

**Comment by flexiondotorg** [comment]
Excellent. Confirmed fixed. Thank you!
