### ISSUE TITLE
Using Compiz & Metacity inactive windows displays borders around buttons and other elements

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#82]
When using Compiz as the window manager some buttons (and other elements) in inactive windows are rendered with light border. See the attached screenshot. This might be limited to CSD windows. The affects Ambiant-MATE and Ambiant-MATE Dark.

![compiz-csd-inactive-windows](https://cloud.githubusercontent.com/assets/304639/24361066/dd6b03c6-1300-11e7-830b-9fede07c7da1.png)

**Comment by raveit65** [comment]
Are those windows in the background?
I have the feeling that we see the backdrop state here, which does not work with marco.
Well i need to install metacity.

**Comment by flexiondotorg** [comment]
@raveit65 The foreground window is MATE Terminal, the rest are background. **Marco works correctly, it is Compiz that exhibits the issue.**

**Comment by raveit65** [comment]
If mate-terminal is the foreground window than the other windows are in background and use the **:backdrop** state :)
Marco don't support this widget state and for this reason you don't see this garbage.
The backdrop state is supported by compiz-0.9x and metacity.
What i mean?
ie **button:backdrop {}**
Hope that makes it clear.....

**Comment by raveit65** [comment]
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/93455330bc2e211dcdc51c2d398a82523b7913dd
Not perfect because we don't have enough dark border images for the backdrop state.
Please test.

**Comment by flexiondotorg** [comment]
Looks much much better! @raveit65 Please make similar modifications to Ambiant-MATE some of the same issues exists there too.

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/633d2d5b80f046e59f5581165f2f16393a9a9b47
I hope i found all wrong backdrop stuff, if not please post the application with a screenshot here.

**Comment by flexiondotorg** [comment]
Thank you, much better :-)
