### ISSUE TITLE
Style Brisk Menu button to match Applications Places System

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#83]
The button for the Brisk Menu is not styled the same as Applications Places System. This issue exists in all 3 themes.

**Comment by raveit65** [comment]
The button use
```
button.flat.toggle {]
```
We need to add a specific style class here to style them as menubar > menuitem, ie.
button.flat.toggle.brisk-button  .

**Comment by flexiondotorg** [comment]
@raveit65 This has been implemented in Brisk Menu 0.3.5.

  * https://github.com/solus-project/brisk-menu/issues/26

Brisk Menu 0.3.5 is available from the development PPA, which you can enable and upgrade to using:

    sudo apt-add-repository ppa:ubuntu-mate-dev/crazy-mate
    sudo apt update
    sudo apt upgrade

**Comment by raveit65** [comment]
Setting for Ambiant-Mate top panel:
```
.mate-panel-menu-bar #PanelApplet button.flat.toggle.brisk-button,
.mate-panel-menu-bar #PanelApplet button.flat.toggle.brisk-button:hover {
    background-image: none;
    background-color: transparent;
    padding: 3px 5px;
    border-width: 1px 1px 1px 0px;
    border-radius: 4px 4px 0 0;
    border-color: transparent;
    border-image: none;
    text-shadow: none;
}

.mate-panel-menu-bar #PanelApplet button.flat.toggle.brisk-button:checked {
    background-color: transparent;
    background-clip: border-box;
    background-image: -gtk-gradient (linear, left top, left bottom,
                                     from (shade (@dark_bg_color, 1.38)),
                                     to (shade (@dark_bg_color, 1.11)));
    box-shadow: inset 0 1px 1px 0 shade (@dark_bg_color, 1.8);
    padding: 3px 5px;
    border-width: 1px 1px 1px 0px;
    border-radius: 4px 4px 0 0;
    border-color: #2e2e2c;
    border-image: none;
    text-shadow: none;
}
```
Sadly border-radius and box-shadow needs to be set reverse for bottom panel, but there is no style class to make it diferent in panel code.

**Comment by flexiondotorg** [comment]
@raveit65 Can you share a screenshot? I've made the changes above and can't see any difference.

**Comment by raveit65** [comment]
![brisk-top](https://cloud.githubusercontent.com/assets/961604/24539025/ce73a15e-15ec-11e7-8265-243d4f5976f5.png)
![brisk-bottom](https://cloud.githubusercontent.com/assets/961604/24539032/da09deac-15ec-11e7-80e9-8a4a596734e9.png)
The new brisk-menu version is installed? ´

**Comment by raveit65** [comment]
I created a branch for testing
https://github.com/flexiondotorg/ubuntu-mate-themes/commit/619bdc6dd8872c70ffc3d747d732e05bc260f6a3

Maybe it's possible to add another style classes like top/bottom/left/right and the applet code knows the panel directions.
Such style classes are used for scrollbar buttons for example.

**Comment by flexiondotorg** [comment]
@raveit65 Yes, updated Brisk and installed your branch. Looks great!

The issue with the button styling button in the bottom panel is consistent with what happens to the default menu bar too, which no one has ever reported an issue about?! So, lets save that fix for another day. 

Please make the brisk button change for Radiant and Ambiant-Dark and merge to master :-)

**Comment by flexiondotorg** [comment]
Closed via https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e006130be13ef463ad8adc3e766594d2bc6d1293 and https://github.com/flexiondotorg/ubuntu-mate-themes/commit/e006130be13ef463ad8adc3e766594d2bc6d1293
