### ISSUE TITLE
Using Compiz & Metacity the scale troughs in the inactive `plank` Preferences window are light

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#84]
When using Compiz or Metacity and the Ambiant-MATE Dark theme opening Plank (the dock) Preferences and then making that window inactive shows that the troughs on scales are light coloured when they should be dark. Looks to be a similar issue to #82.

## How to reproduce

  * Using Ubuntu MATE 17.04 start MATE Tweak and then select the Cupertino layout. 
  * Plank will appear as the bottom of the screen.
  * Right click the anchor icon and select Preferences
  * While the Plank Preferences window is open, click the desktop or another window so it becomes inactive.

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/17e9d0de7a619f58d5c7c883ab3d14ad9239f42a

**Comment by flexiondotorg** [comment]
Thank you. Confirmed fixed :-)
